#!/usr/bin/env -S uv run --quiet --with markdown --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["markdown>=3.6"]
# ///
"""
llm-wiki HTML builder.

Walks wiki/{entities,concepts,sources,analysis}/*.md + wiki/{index,log}.md and
generates a mirrored tree under wiki/html/ using the shared style.css.

Hand-crafted HTML pages (e.g. wiki/html/sources/src-nanobot-architecture.html
with Mermaid diagrams) are preserved: build.py only overwrites files that
either don't exist or carry the auto-generated marker.

Run: ./wiki/html-assets/build.py            (idempotent)
     ./wiki/html-assets/build.py --force    (overwrite everything)
"""
from __future__ import annotations

import argparse
import html as htmllib
import json
import math
import os
import re
import shutil
import sys
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path

import markdown as md

ROOT = Path(__file__).resolve().parent.parent.parent
WIKI = ROOT / "wiki"
OUT = WIKI / "html"
ASSETS_REL = "html-assets/style.css"

AUTO_MARKER = "<!-- generated by wiki/html-assets/build.py -->"
STYLESHEET_RE = re.compile(r'href="(?:\.\./)*html-assets/style\.css"')

CATEGORIES = ("entities", "concepts", "sources", "analysis")
CATEGORY_LABELS = {
    "entities": "实体",
    "concepts": "概念",
    "sources": "源文件",
    "analysis": "分析",
}

TOPIC_GROUPS = [
    {
        "title": "AI Agent / Memory",
        "description": "长期记忆、MCP、coding agent、Agent framework 与个人 AI 工具链。",
        "tags": {"agent-memory", "ai-agent", "mcp", "claude-code", "agent-framework"},
        "preferred": (
            "agent-memory-project-map",
            "ai-agent-frameworks-map",
            "agent-memory",
            "claude-code",
        ),
    },
    {
        "title": "Agent Runtime / Sandbox",
        "description": "Agent 会话编排、沙箱隔离、凭据托管、网关治理和多 Agent 协作。",
        "tags": {"agent-runtime", "agent-sandbox", "sandbox", "multi-agent", "ai-gateway"},
        "preferred": (
            "agent-runtime-sandbox-project-map",
            "agent-sandbox",
            "agentgateway",
            "agent-credential-isolation",
        ),
    },
    {
        "title": "LLM Inference / Serving",
        "description": "推理服务、KV cache、PagedAttention、RadixAttention 和多云 GPU 编排。",
        "tags": {"llm-inference", "llm-serving", "kv-cache", "ai-infra", "gpu"},
        "preferred": (
            "llm-inference-serving-project-map",
            "llm-inference",
            "paged-attention",
            "radix-attention",
        ),
    },
    {
        "title": "Kubernetes / Cloud Native",
        "description": "Kubernetes、GitOps、controller/operator、GPU 资源栈、安全和可观测。",
        "tags": {"kubernetes", "cloud-native", "gitops", "controller", "operator"},
        "preferred": (
            "kubernetes",
            "gitops",
            "argocd",
            "cloud-native-security",
        ),
    },
]


# ── Frontmatter ──────────────────────────────────────────────────
FRONTMATTER_RE = re.compile(r"\A[^\n]*?---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass
class Frontmatter:
    title: str = ""
    tags: list[str] = field(default_factory=list)
    date: str = ""
    sources: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)


def parse_frontmatter(text: str) -> tuple[Frontmatter, str]:
    """Tolerant: accepts garbage chars before the first --- (e.g. kubernetes.md `k2---`)."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return Frontmatter(), text
    raw = m.group(1)
    body = text[m.end():]
    fm = Frontmatter()
    for line in raw.splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k, v = k.strip(), v.strip()
        if not v:
            continue
        if k == "title":
            fm.title = v.strip('"').strip("'")
        elif k == "date":
            fm.date = v.strip('"').strip("'")
        elif k in ("tags", "sources", "related"):
            items = re.findall(r"\[\[([^\]]+)\]\]|\"([^\"]+)\"|'([^']+)'|([^,\[\]\s]+)", v)
            flat = [a or b or c or d for (a, b, c, d) in items]
            flat = [x.strip().strip('"').strip("'").strip("[").strip("]") for x in flat if x]
            flat = [x for x in flat if x]
            setattr(fm, k, flat)
    return fm, body


# ── Wikilink resolution ──────────────────────────────────────────
class Resolver:
    """Index every wiki/*.md by stem → its category (entities/concepts/sources/analysis)."""

    def __init__(self) -> None:
        self.index: dict[str, str] = {}
        self.canonical: dict[str, str] = {}
        for cat in CATEGORIES:
            d = WIKI / cat
            if not d.is_dir():
                continue
            for f in d.glob("*.md"):
                self.index[f.stem] = cat
                self.index[f.stem.lower()] = cat
                self.canonical[f.stem] = f.stem
                self.canonical[f.stem.lower()] = f.stem

    def resolve(self, target: str) -> tuple[str, str] | None:
        """Return (category, canonical stem) for a target page; None if not found."""
        stem = target.strip()
        if "|" in stem:
            stem, _ = stem.split("|", 1)
        if "#" in stem:
            stem, _ = stem.split("#", 1)
        stem = stem.strip()
        if not stem:
            return None
        cat = self.index.get(stem) or self.index.get(stem.lower())
        if not cat:
            return None
        return cat, self.canonical.get(stem) or self.canonical.get(stem.lower()) or stem

    def href(self, target: str, *, from_cat: str | None) -> str | None:
        """Return relative href from a page in from_cat to target page; None if not found."""
        resolved = self.resolve(target)
        if not resolved:
            return None
        cat, real_stem = resolved
        target_path = f"{cat}/{real_stem}.html"
        if from_cat is None:
            return target_path  # called from wiki/html/index.html
        return f"../{target_path}"


# ── Wikilink preprocessing ───────────────────────────────────────
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


def rewrite_wikilinks(body: str, resolver: Resolver, from_cat: str | None) -> str:
    def repl(m: re.Match) -> str:
        target = m.group(1).strip()
        label = target
        if "|" in target:
            target, label = target.split("|", 1)
            target = target.strip()
            label = label.strip()
        href = resolver.href(target, from_cat=from_cat)
        if href:
            return f'<a class="wikilink" href="{href}">{htmllib.escape(label)}</a>'
        return f'<span class="wikilink wikilink-missing" title="未建页：{htmllib.escape(target)}">{htmllib.escape(label)}</span>'

    return WIKILINK_RE.sub(repl, body)


# ── TOC extraction ───────────────────────────────────────────────
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def slugify(s: str) -> str:
    s = re.sub(r"[<>&\"']+", "", s)
    s = re.sub(r"\s+", "-", s.strip().lower())
    s = re.sub(r"[^a-z0-9\u4e00-\u9fa5\-_]", "", s)
    return s[:80] or "section"


def extract_toc(body: str) -> list[tuple[int, str, str]]:
    """Return [(level, text, slug)] for h2/h3 (skip h1; it's the page title)."""
    toc = []
    seen: dict[str, int] = {}
    for m in HEADING_RE.finditer(body):
        hashes, text = m.group(1), m.group(2)
        level = len(hashes)
        if level < 2 or level > 3:
            continue
        slug = slugify(text)
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 1
        toc.append((level, text, slug))
    return toc


def inject_heading_ids(body: str) -> str:
    """Add {#slug} to h2/h3 so python-markdown's toc extension picks them up."""
    seen: dict[str, int] = {}

    def repl(m: re.Match) -> str:
        hashes, text = m.group(1), m.group(2)
        level = len(hashes)
        if level < 2 or level > 3:
            return m.group(0)
        # Strip wikilink syntax for slugification only
        plain = WIKILINK_RE.sub(r"\1", text)
        slug = slugify(plain)
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 1
        return f"{hashes} {text} {{#{slug}}}"

    return HEADING_RE.sub(repl, body)


# ── HTML shell ───────────────────────────────────────────────────
SHELL = """<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title} · llm-wiki</title>
  <link rel="stylesheet" href="{style_href}" />
{extra_head}
{auto_marker}
</head>
<body>

<header class="topbar">
  <a class="brand" href="{home_href}"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">{breadcrumb}</span>
  <span class="spacer"></span>
  <span class="meta">{meta_right}</span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<div class="layout">
  <main class="content">

  <header class="page-header">
    <h1>{title}</h1>
    {subtitle_html}
    {tags_html}
  </header>

  {body_html}

  {related_html}

  <div class="footer">
    🦊 llm-wiki · {category_label} · <a href="{md_href}">查看 Markdown 源</a>
  </div>
  </main>

  {sidebar_html}
</div>

<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});

  const tocLinks = document.querySelectorAll(".toc a");
  const headings = Array.from(document.querySelectorAll("h2[id], h3[id]"));
  function updateActive() {{
    let active = headings[0];
    for (const h of headings) {{
      if (h.getBoundingClientRect().top - 100 <= 0) active = h;
    }}
    if (!active) return;
    tocLinks.forEach((a) =>
      a.classList.toggle("active", a.getAttribute("href") === "#" + active.id)
    );
  }}
  window.addEventListener("scroll", updateActive, {{ passive: true }});
  updateActive();
</script>

</body>
</html>
"""


def render_toc(toc: list[tuple[int, str, str]]) -> str:
    if not toc:
        return ""
    items = []
    for level, text, slug in toc:
        # strip wikilink syntax for TOC label
        label = WIKILINK_RE.sub(r"\1", text)
        cls = "level-3" if level == 3 else ""
        items.append(f'<li class="{cls}"><a href="#{slug}">{htmllib.escape(label)}</a></li>')
    return (
        '<aside class="toc"><h4>本页目录</h4><ul>'
        + "".join(items)
        + "</ul></aside>"
    )


def graph_node_href(node: dict[str, object], from_cat: str | None) -> str:
    href = str(node["href"])
    if from_cat is None:
        return href
    return f"../{href}"


def render_page_relations(page: Page, graph_data: dict[str, object] | None) -> str:
    if not graph_data or page.category == "ROOT":
        return ""
    current_id = page.md_path.stem
    nodes = {str(node["id"]): node for node in graph_data["nodes"]}
    if current_id not in nodes:
        return ""

    inbound = [edge for edge in graph_data["edges"] if edge["target"] == current_id and edge["source"] in nodes]
    outbound = [edge for edge in graph_data["edges"] if edge["source"] == current_id and edge["target"] in nodes]
    neighbor_ids: list[str] = []
    for edge in outbound:
        target = str(edge["target"])
        if target not in neighbor_ids:
            neighbor_ids.append(target)
    for edge in inbound:
        source = str(edge["source"])
        if source not in neighbor_ids:
            neighbor_ids.append(source)

    neighbors = [nodes[node_id] for node_id in neighbor_ids[:12]]
    mini_nodes = neighbors[:8]
    graph_href = f"../graph.html?focus={htmllib.escape(current_id, quote=True)}"

    if mini_nodes:
        center_x = 120
        center_y = 82
        radius = 58
        lines = []
        circles = [
            '<circle class="mini-node mini-node-current" cx="120" cy="82" r="10" />',
            f'<text x="120" y="108" text-anchor="middle">{htmllib.escape(page.title[:16])}</text>',
        ]
        for index, node in enumerate(mini_nodes):
            angle = (index / max(len(mini_nodes), 1)) * 6.28318 - 1.5708
            x = center_x + radius * math.cos(angle)
            y = center_y + radius * math.sin(angle)
            category = htmllib.escape(str(node["category"]), quote=True)
            lines.append(f'<line x1="{center_x:.1f}" y1="{center_y:.1f}" x2="{x:.1f}" y2="{y:.1f}" />')
            circles.append(
                f'<circle class="mini-node mini-node-{category}" cx="{x:.1f}" cy="{y:.1f}" r="7">'
                f'<title>{htmllib.escape(str(node["title"]))}</title></circle>'
            )
        mini_svg = (
            '<svg class="mini-graph" viewBox="0 0 240 150" role="img" aria-label="本页一跳关系图">'
            + "".join(lines)
            + "".join(circles)
            + "</svg>"
        )
    else:
        mini_svg = '<p class="side-empty">本页还没有可解析的 wiki 关系。</p>'

    def render_items(edges: list[dict[str, str]], direction: str) -> str:
        if not edges:
            return '<p class="side-empty">暂无。</p>'
        items = []
        for edge in edges[:8]:
            node_id = edge["source"] if direction == "in" else edge["target"]
            node = nodes.get(node_id)
            if not node:
                continue
            items.append(
                '<li>'
                f'<a href="{graph_node_href(node, page.category)}">{htmllib.escape(str(node["title"]))}</a>'
                f'<span>{htmllib.escape(str(node["category_label"]))} · {htmllib.escape(str(edge["kind"]))}</span>'
                '</li>'
            )
        return f'<ul class="side-link-list">{"".join(items)}</ul>' if items else '<p class="side-empty">暂无。</p>'

    return (
        '<aside class="side-panel page-relations">'
        '<div class="side-panel-head"><h3>关系图谱</h3>'
        f'<a href="{graph_href}">全局打开</a></div>'
        f'{mini_svg}'
        '<h4>它指向</h4>'
        f'{render_items(outbound, "out")}'
        '<h4>反向链接</h4>'
        f'{render_items(inbound, "in")}'
        '</aside>'
    )


def render_sidebar(toc_html: str, relation_html: str) -> str:
    if not toc_html and not relation_html:
        return ""
    return f'<aside class="right-rail">{relation_html}{toc_html}</aside>'


def render_tags(tags: list[str]) -> str:
    if not tags:
        return ""
    chips = "".join(f'<span class="tag">{htmllib.escape(t)}</span>' for t in tags)
    return f'<div class="tags">{chips}</div>'


def render_related(items: list[str], resolver: Resolver, from_cat: str | None) -> str:
    if not items:
        return ""
    lis = []
    for raw in items:
        target = raw.strip().strip("[").strip("]").strip()
        if not target:
            continue
        href = resolver.href(target, from_cat=from_cat)
        if href:
            lis.append(f'<li><a class="wikilink" href="{href}">{htmllib.escape(target)}</a></li>')
        else:
            lis.append(
                f'<li><span class="wikilink wikilink-missing" title="未建页：{htmllib.escape(target)}">'
                f'{htmllib.escape(target)}</span></li>'
            )
    return (
        '<section class="related-panel" aria-labelledby="related-frontmatter">'
        '<h2 id="related-frontmatter">相关页面</h2>'
        f'<ul>{"".join(lis)}</ul>'
        '</section>'
    )


def render_subtitle(fm: Frontmatter) -> str:
    parts = []
    if fm.date:
        parts.append(htmllib.escape(fm.date))
    if fm.sources:
        srcs = "、".join(htmllib.escape(s) for s in fm.sources)
        parts.append(f"来源：{srcs}")
    if not parts:
        return ""
    return f'<p class="page-meta">{" · ".join(parts)}</p>'


# ── Page builder ─────────────────────────────────────────────────
@dataclass
class Page:
    md_path: Path
    category: str  # entities / concepts / sources / analysis / ROOT (for index/log)
    fm: Frontmatter
    body_md: str
    title: str


@dataclass
class PageMeta:
    title: str
    href: str
    category: str
    category_label: str
    stem: str
    tags: list[str]
    date: str
    description: str = ""


@dataclass
class GraphNode:
    id: str
    title: str
    category: str
    category_label: str
    href: str
    tags: list[str]
    date: str
    description: str
    degree: int = 0
    inbound: int = 0
    outbound: int = 0


@dataclass(frozen=True)
class GraphEdge:
    source: str
    target: str
    kind: str


RELATED_SECTION_RE = re.compile(r"^##\s+相关页面\s*$.*?(?=^##\s+|\Z)", re.MULTILINE | re.DOTALL)


def strip_markdown_related_section(body: str) -> str:
    """Use frontmatter related links as the single generated related panel."""
    return RELATED_SECTION_RE.sub("", body).rstrip() + "\n"


def build_page(page: Page, resolver: Resolver, graph_data: dict[str, object] | None = None) -> str:
    body_md = strip_markdown_related_section(page.body_md) if page.fm.related else page.body_md
    body_with_ids = inject_heading_ids(body_md)
    body_with_links = rewrite_wikilinks(body_with_ids, resolver, from_cat=page.category if page.category != "ROOT" else None)

    # Markdown → HTML
    converter = md.Markdown(
        extensions=["fenced_code", "tables", "attr_list", "admonition", "sane_lists", "nl2br"],
        output_format="html5",
    )
    body_html = converter.convert(body_with_links)

    # Drop the first <h1> if present; we render our own
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)
    body_html = re.sub(r"(<table>.*?</table>)", r'<div class="table-wrap">\1</div>', body_html, flags=re.DOTALL)

    toc = extract_toc(body_md)
    toc_html = render_toc(toc)
    relation_html = render_page_relations(page, graph_data)
    sidebar_html = render_sidebar(toc_html, relation_html)

    is_root = page.category == "ROOT"
    style_href = ASSETS_REL if is_root else f"../{ASSETS_REL}"
    home_href = "./index.html" if is_root else "../index.html"
    md_href = f"../{page.md_path.name}" if is_root else f"../../{page.category}/{page.md_path.name}"
    breadcrumb = "wiki" if is_root else f"wiki · {page.category}"
    meta_right = page.fm.date or ""
    category_label = "ROOT" if is_root else page.category

    return SHELL.format(
        title=htmllib.escape(page.title),
        style_href=style_href,
        extra_head="",
        auto_marker=AUTO_MARKER,
        home_href=home_href,
        breadcrumb=htmllib.escape(breadcrumb),
        meta_right=htmllib.escape(meta_right),
        subtitle_html=render_subtitle(page.fm),
        tags_html=render_tags(page.fm.tags),
        body_html=body_html,
        related_html=render_related(page.fm.related, resolver, from_cat=page.category if not is_root else None),
        category_label=category_label,
        md_href=md_href,
        sidebar_html=sidebar_html,
    )


def load_page(md_path: Path, category: str) -> Page:
    text = md_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    # Title: frontmatter title > first h1 > filename
    title = fm.title
    if not title:
        h1 = re.search(r"^#\s+(.+?)\s*$", body, re.MULTILINE)
        title = h1.group(1).strip() if h1 else md_path.stem
    return Page(md_path=md_path, category=category, fm=fm, body_md=body, title=title)


def should_write(dst: Path, force: bool) -> bool:
    if force or not dst.exists():
        return True
    head = dst.read_text(encoding="utf-8", errors="replace")[:2000]
    return AUTO_MARKER in head


def sync_html_assets(dry_run: bool) -> None:
    src = WIKI / "html-assets" / "style.css"
    dst = OUT / "html-assets" / "style.css"
    if dry_run:
        print(f"  would copy: {dst.relative_to(ROOT)}")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    print(f"  ✓ {dst.relative_to(ROOT)}")


def normalize_stylesheet_href(dst: Path, dry_run: bool) -> bool:
    if not dst.exists():
        return False
    style_href = Path(os.path.relpath(OUT / ASSETS_REL, dst.parent)).as_posix()
    text = dst.read_text(encoding="utf-8")
    next_text = STYLESHEET_RE.sub(f'href="{style_href}"', text)
    if next_text == text:
        return False
    if dry_run:
        print(f"  would update asset link: {dst.relative_to(ROOT)}")
        return True
    dst.write_text(next_text, encoding="utf-8")
    print(f"  ✓ asset link: {dst.relative_to(ROOT)}")
    return True


# ── Site index page ──────────────────────────────────────────────
class IndexDescriptionParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.descriptions: dict[str, str] = {}
        self._in_li = False
        self._href: str | None = None
        self._text_parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attrs_dict = dict(attrs)
        if tag == "li":
            self._in_li = True
            self._href = None
            self._text_parts = []
            return
        if tag == "a" and self._in_li and self._href is None:
            classes = (attrs_dict.get("class") or "").split()
            href = attrs_dict.get("href")
            if "wikilink" in classes and href:
                self._href = href

    def handle_data(self, data: str) -> None:
        if self._in_li:
            self._text_parts.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag != "li" or not self._in_li:
            return
        text = re.sub(r"\s+", " ", "".join(self._text_parts)).strip()
        if self._href and "—" in text:
            _, desc = text.split("—", 1)
            self.descriptions[htmllib.unescape(self._href)] = desc.strip()
        self._in_li = False
        self._href = None
        self._text_parts = []


def extract_index_descriptions(index_html: str) -> dict[str, str]:
    parser = IndexDescriptionParser()
    parser.feed(index_html)
    parser.close()
    return parser.descriptions


def escape_script_json(json_text: str) -> str:
    return (
        json_text.replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def collect_page_meta(descriptions: dict[str, str] | None = None) -> list[PageMeta]:
    descriptions = descriptions or {}
    pages: list[PageMeta] = []
    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        for f in sorted(src_dir.glob("*.md")):
            p = load_page(f, cat)
            href = f"{cat}/{f.stem}.html"
            pages.append(
                PageMeta(
                    title=p.title,
                    href=href,
                    category=cat,
                    category_label=CATEGORY_LABELS.get(cat, cat),
                    stem=f.stem,
                    tags=p.fm.tags,
                    date=p.fm.date,
                    description=descriptions.get(href, ""),
                )
            )
    return pages


def collect_index_descriptions(resolver: Resolver) -> tuple[str, dict[str, str]]:
    index_md = (WIKI / "index.md").read_text(encoding="utf-8")
    _fm, body = parse_frontmatter(index_md)
    body_resolved = rewrite_wikilinks(body, resolver, from_cat=None)
    body_with_ids = inject_heading_ids(body_resolved)

    converter = md.Markdown(extensions=["fenced_code", "tables", "attr_list", "sane_lists"], output_format="html5")
    body_html = converter.convert(body_with_ids)
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)
    body_html = re.sub(r"(<table>.*?</table>)", r'<div class="table-wrap">\1</div>', body_html, flags=re.DOTALL)
    return body_html, extract_index_descriptions(body_html)


def collect_graph_data(resolver: Resolver, descriptions: dict[str, str] | None = None) -> dict[str, object]:
    descriptions = descriptions or {}
    nodes: dict[str, GraphNode] = {}
    edges_by_pair: dict[tuple[str, str], str] = {}

    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        for md_path in sorted(src_dir.glob("*.md")):
            page = load_page(md_path, cat)
            node_id = md_path.stem
            href = f"{cat}/{node_id}.html"
            nodes[node_id] = GraphNode(
                id=node_id,
                title=page.title,
                category=cat,
                category_label=CATEGORY_LABELS.get(cat, cat),
                href=href,
                tags=page.fm.tags,
                date=page.fm.date,
                description=descriptions.get(href, ""),
            )

            page_edges: dict[tuple[str, str], str] = {}
            for raw in WIKILINK_RE.findall(page.body_md):
                resolved = resolver.resolve(raw)
                if not resolved:
                    continue
                _target_cat, target_stem = resolved
                if target_stem != node_id:
                    page_edges.setdefault((node_id, target_stem), "wikilink")
            for raw in page.fm.related:
                resolved = resolver.resolve(raw)
                if not resolved:
                    continue
                _target_cat, target_stem = resolved
                if target_stem != node_id:
                    page_edges[(node_id, target_stem)] = "related"
            edges_by_pair.update(page_edges)

    inbound: dict[str, set[str]] = {node_id: set() for node_id in nodes}
    outbound: dict[str, set[str]] = {node_id: set() for node_id in nodes}
    for source, target in edges_by_pair:
        if source not in nodes or target not in nodes:
            continue
        outbound[source].add(target)
        inbound[target].add(source)

    for node_id, node in nodes.items():
        node.inbound = len(inbound[node_id])
        node.outbound = len(outbound[node_id])
        node.degree = len(inbound[node_id] | outbound[node_id])

    edges = [
        GraphEdge(source=source, target=target, kind=kind)
        for (source, target), kind in sorted(edges_by_pair.items())
        if source in nodes and target in nodes
    ]
    return {
        "nodes": [node.__dict__ for node in sorted(nodes.values(), key=lambda n: (n.category, n.title.lower()))],
        "edges": [edge.__dict__ for edge in edges],
        "categories": [
            {
                "id": cat,
                "label": CATEGORY_LABELS.get(cat, cat),
                "count": sum(1 for node in nodes.values() if node.category == cat),
            }
            for cat in CATEGORIES
        ],
    }


def build_topic_groups(pages: list[PageMeta]) -> list[dict[str, object]]:
    by_stem = {p.stem: p for p in pages}
    groups: list[dict[str, object]] = []
    for cfg in TOPIC_GROUPS:
        tagset = cfg["tags"]
        preferred_stems = cfg["preferred"]
        preferred_set = set(preferred_stems)
        matches = [
            p for p in pages
            if tagset.intersection(set(p.tags))
            or any(token in p.title.lower() for token in tagset)
            or p.stem in preferred_set
        ]
        unique: dict[str, PageMeta] = {p.href: p for p in matches}
        ordered = [by_stem[s] for s in preferred_stems if s in by_stem]
        ordered.extend(
            sorted(
                (p for p in unique.values() if p.stem not in preferred_set),
                key=lambda p: (p.category != "analysis", p.title.lower()),
            )
        )
        groups.append(
            {
                "title": cfg["title"],
                "description": cfg["description"],
                "count": len(unique),
                "links": ordered[:4],
            }
        )
    return groups


LOG_ENTRY_RE = re.compile(r"^## \[(?P<date>\d{4}-\d{2}-\d{2})\]\s+(?P<kind>[^|]+)\|\s*(?P<title>.+)$")


def parse_recent_updates(limit: int = 8) -> list[dict[str, str]]:
    log_path = WIKI / "log.md"
    if not log_path.exists():
        return []
    indexed_updates: list[tuple[str, int, dict[str, str]]] = []
    for line_index, line in enumerate(log_path.read_text(encoding="utf-8").splitlines()):
        m = LOG_ENTRY_RE.match(line.strip())
        if not m:
            continue
        date = m.group("date")
        indexed_updates.append(
            (
                date,
                line_index,
                {
                    "date": date,
                    "kind": m.group("kind").strip(),
                    "title": m.group("title").strip(),
                    "href": "log.html",
                },
            )
        )
    indexed_updates.sort(key=lambda entry: (entry[0], entry[1]), reverse=True)
    return [update for _, _, update in indexed_updates[:limit]]


def build_site_stats(pages: list[PageMeta]) -> list[tuple[str, int]]:
    return [
        ("全部页面", len(pages)),
        ("实体", sum(1 for p in pages if p.category == "entities")),
        ("概念", sum(1 for p in pages if p.category == "concepts")),
        ("源文件", sum(1 for p in pages if p.category == "sources")),
        ("分析", sum(1 for p in pages if p.category == "analysis")),
    ]


def esc(value: object) -> str:
    return htmllib.escape(str(value), quote=True)


def render_stat_strip(stats: list[tuple[str, int]]) -> str:
    return '<div class="stats-strip">' + "".join(
        f'<div class="stat"><strong>{count}</strong><span>{esc(label)}</span></div>'
        for label, count in stats
    ) + "</div>"


def render_topic_grid(topic_groups: list[dict[str, object]]) -> str:
    cards = []
    for group in topic_groups:
        links = group["links"]
        link_html = "".join(
            f'<a href="{esc(p.href)}">{esc(p.title)}</a>'
            for p in links
        )
        cards.append(
            '<section class="topic-card">'
            f'<div class="topic-card-head"><h2>{esc(group["title"])}</h2>'
            f'<span>{esc(group["count"])} pages</span></div>'
            f'<p>{esc(group["description"])}</p>'
            f'<div class="topic-links">{link_html}</div>'
            '</section>'
        )
    return '<div class="topic-grid">' + "".join(cards) + "</div>"


def render_recent_updates(updates: list[dict[str, str]]) -> str:
    if not updates:
        return ""
    items = "".join(
        '<li>'
        f'<time>{esc(item["date"])}</time>'
        f'<a href="{esc(item["href"])}">{esc(item["title"])}</a>'
        f'<span>{esc(item["kind"])}</span>'
        '</li>'
        for item in updates
    )
    return f'<section class="panel recent-updates"><h2>最近更新</h2><ul>{items}</ul></section>'


def render_reading_paths(topic_groups: list[dict[str, object]]) -> str:
    items = []
    for group in topic_groups:
        first_links = group["links"][:3]
        links = " ".join(
            f'<a href="{esc(p.href)}">{esc(p.title)}</a>'
            for p in first_links
        )
        items.append(
            '<li>'
            f'<strong>{esc(group["title"])}</strong>'
            f'<p>{esc(group["description"])}</p>'
            f'<div class="inline-links">{links}</div>'
            '</li>'
        )
    return '<section class="panel reading-paths"><h2>推荐阅读路径</h2><ol>' + "".join(items) + "</ol></section>"


GRAPH_PAGE_SCRIPT = r"""
(() => {
  const data = JSON.parse(document.getElementById("graph-data").textContent);
  const svg = document.getElementById("knowledge-graph");
  const viewport = document.getElementById("graph-viewport");
  const searchInput = document.getElementById("graph-search");
  const resetButton = document.getElementById("graph-reset");
  const focusButton = document.getElementById("graph-focus");
  const zoomInButton = document.getElementById("graph-zoom-in");
  const zoomOutButton = document.getElementById("graph-zoom-out");
  const fitButton = document.getElementById("graph-fit");
  const workbench = document.querySelector(".graph-workbench");
  const inspector = document.getElementById("graph-inspector");
  const totals = document.getElementById("graph-totals");
  const categoryButtons = Array.from(document.querySelectorAll("[data-graph-category]"));
  const nodeById = new Map(data.nodes.map((node) => [node.id, { ...node }]));
  const allEdges = data.edges.filter((edge) => nodeById.has(edge.source) && nodeById.has(edge.target));
  const categories = new Set(data.categories.map((cat) => cat.id));
  const activeCategories = new Set(categories);
  const colorByCategory = {
    entities: "#6ea8fe",
    concepts: "#8ad97a",
    sources: "#f0b75d",
    analysis: "#c99cff",
  };

  let visibleNodes = [];
  let visibleEdges = [];
  let selectedId = null;
  let highlightedId = null;
  let scale = 1;
  let panX = 0;
  let panY = 0;
  let drag = null;
  let panning = null;
  let focusMode = true;
  const positionsReady = new Set();
  const initialFocus = new URLSearchParams(window.location.search).get("focus");
  if (initialFocus && nodeById.has(initialFocus)) {
    selectedId = initialFocus;
    searchInput.value = nodeById.get(initialFocus).title;
  }

  const esc = (value) => String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
  const shortLabel = (value) => {
    const text = String(value ?? "");
    return text.length > 26 ? `${text.slice(0, 25)}...` : text;
  };

  function matchesQuery(node, query) {
    if (!query) return true;
    return [node.title, node.id, node.category, node.category_label, node.description, ...(node.tags || [])]
      .join(" ")
      .toLowerCase()
      .includes(query);
  }

  function getVisibleData() {
    const query = searchInput.value.trim().toLowerCase();
    const directMatches = new Set(
      data.nodes
        .filter((node) => activeCategories.has(node.category) && matchesQuery(node, query))
        .map((node) => node.id)
    );
    const visibleIds = new Set(directMatches);

    if (query) {
      for (const edge of allEdges) {
        if (directMatches.has(edge.source) && activeCategories.has(nodeById.get(edge.target).category)) {
          visibleIds.add(edge.target);
        }
        if (directMatches.has(edge.target) && activeCategories.has(nodeById.get(edge.source).category)) {
          visibleIds.add(edge.source);
        }
      }
    }

    const nodes = data.nodes.filter((node) => visibleIds.has(node.id)).map((node) => nodeById.get(node.id));
    const idSet = new Set(nodes.map((node) => node.id));
    const edges = allEdges.filter((edge) => idSet.has(edge.source) && idSet.has(edge.target));
    return { nodes, edges };
  }

  function seedPositions(nodes) {
    const rect = svg.getBoundingClientRect();
    const width = Math.max(rect.width, 720);
    const height = Math.max(rect.height, 620);
    const lanes = Array.from(categories);
    const laneWidth = width / Math.max(lanes.length, 1);
    const ordered = [...nodes].sort((a, b) => (b.degree - a.degree) || a.title.localeCompare(b.title));

    ordered.forEach((node, index) => {
      if (positionsReady.has(node.id)) return;
      const lane = Math.max(0, lanes.indexOf(node.category));
      const row = Math.floor(index / Math.max(lanes.length, 1));
      const jitter = ((index * 37) % 100) / 100;
      node.x = laneWidth * lane + laneWidth * (0.32 + jitter * 0.36);
      node.y = 92 + (row * 92 + jitter * 48) % Math.max(height - 180, 360);
      positionsReady.add(node.id);
    });
  }

  function runLayout(nodes, edges) {
    seedPositions(nodes);
    const rect = svg.getBoundingClientRect();
    const width = Math.max(rect.width, 720);
    const height = Math.max(rect.height, 620);
    const links = edges.map((edge) => [nodeById.get(edge.source), nodeById.get(edge.target)]);

    for (let step = 0; step < 170; step += 1) {
      const alpha = 1 - step / 170;
      for (let i = 0; i < nodes.length; i += 1) {
        const a = nodes[i];
        for (let j = i + 1; j < nodes.length; j += 1) {
          const b = nodes[j];
          let dx = (a.x || 0) - (b.x || 0);
          let dy = (a.y || 0) - (b.y || 0);
          let distance = Math.max(Math.sqrt(dx * dx + dy * dy), 18);
          const force = (1800 / (distance * distance)) * alpha;
          dx /= distance;
          dy /= distance;
          a.x += dx * force;
          a.y += dy * force;
          b.x -= dx * force;
          b.y -= dy * force;
        }
      }

      for (const [source, target] of links) {
        const dx = (target.x || 0) - (source.x || 0);
        const dy = (target.y || 0) - (source.y || 0);
        const distance = Math.max(Math.sqrt(dx * dx + dy * dy), 1);
        const ideal = 122 + Math.min((source.degree + target.degree) * 4, 72);
        const force = (distance - ideal) * 0.014 * alpha;
        const nx = dx / distance;
        const ny = dy / distance;
        source.x += nx * force;
        source.y += ny * force;
        target.x -= nx * force;
        target.y -= ny * force;
      }

      for (const node of nodes) {
        const lane = Array.from(categories).indexOf(node.category);
        const laneX = width * ((lane + 0.5) / Math.max(categories.size, 1));
        node.x += (laneX - node.x) * 0.012 * alpha;
        node.y += (height / 2 - node.y) * 0.006 * alpha;
        node.x = Math.max(42, Math.min(width - 42, node.x));
        node.y = Math.max(42, Math.min(height - 42, node.y));
      }
    }
  }

  function edgeClass(edge) {
    if (!selectedId && !highlightedId) return "";
    const active = selectedId || highlightedId;
    return edge.source === active || edge.target === active ? "is-connected" : "is-dimmed";
  }

  function applyTransform() {
    viewport.setAttribute("transform", `translate(${panX} ${panY}) scale(${scale})`);
  }

  function fitView() {
    if (!visibleNodes.length) {
      scale = 1;
      panX = 0;
      panY = 0;
      applyTransform();
      return;
    }
    const rect = svg.getBoundingClientRect();
    const minX = Math.min(...visibleNodes.map((node) => node.x || 0));
    const maxX = Math.max(...visibleNodes.map((node) => node.x || 0));
    const minY = Math.min(...visibleNodes.map((node) => node.y || 0));
    const maxY = Math.max(...visibleNodes.map((node) => node.y || 0));
    const padding = focusMode ? 72 : 48;
    const graphWidth = Math.max(maxX - minX, 1);
    const graphHeight = Math.max(maxY - minY, 1);
    scale = Math.min(
      1.2,
      Math.max(
        0.5,
        Math.min((rect.width - padding * 2) / graphWidth, (rect.height - padding * 2) / graphHeight)
      )
    );
    panX = (rect.width - graphWidth * scale) / 2 - minX * scale;
    panY = (rect.height - graphHeight * scale) / 2 - minY * scale;
    applyTransform();
  }

  function zoomBy(multiplier) {
    const rect = svg.getBoundingClientRect();
    const px = rect.width / 2;
    const py = rect.height / 2;
    const nextScale = Math.min(2.8, Math.max(0.42, scale * multiplier));
    panX = px - (px - panX) * (nextScale / scale);
    panY = py - (py - panY) * (nextScale / scale);
    scale = nextScale;
    applyTransform();
  }

  function nodeRadius(node) {
    return 6 + Math.min(Math.sqrt(Math.max(node.degree, 1)) * 2.6, 13);
  }

  function drawPositions() {
    viewport.querySelectorAll("[data-edge]").forEach((line) => {
      const source = nodeById.get(line.dataset.source);
      const target = nodeById.get(line.dataset.target);
      line.setAttribute("x1", source.x);
      line.setAttribute("y1", source.y);
      line.setAttribute("x2", target.x);
      line.setAttribute("y2", target.y);
    });
    viewport.querySelectorAll("[data-node]").forEach((group) => {
      const node = nodeById.get(group.dataset.node);
      group.setAttribute("transform", `translate(${node.x} ${node.y})`);
    });
  }

  function renderInspector(nodeId) {
    const node = nodeId ? nodeById.get(nodeId) : null;
    if (!node) {
      const top = [...data.nodes].sort((a, b) => b.degree - a.degree).slice(0, 8);
      inspector.innerHTML = `
        <h2>图谱概览</h2>
        <p>${esc(data.nodes.length)} 个页面，${esc(data.edges.length)} 条页面关系。搜索会保留命中页面的一跳邻居，便于理解上下文。</p>
        <h3>高连接页面</h3>
        <div class="graph-link-list">
          ${top.map((item) => `<a href="${esc(item.href)}">${esc(item.title)}<span>${esc(item.category_label)} · ${esc(item.degree)}</span></a>`).join("")}
        </div>
      `;
      return;
    }

    const inbound = visibleEdges.filter((edge) => edge.target === node.id).map((edge) => nodeById.get(edge.source));
    const outbound = visibleEdges.filter((edge) => edge.source === node.id).map((edge) => nodeById.get(edge.target));
    const tags = (node.tags || []).slice(0, 8).map((tag) => `<span class="tag">${esc(tag)}</span>`).join("");
    inspector.innerHTML = `
      <div class="graph-inspector-head">
        <span class="graph-node-kind">${esc(node.category_label)}</span>
        <a href="${esc(node.href)}">打开页面</a>
      </div>
      <h2>${esc(node.title)}</h2>
      ${node.description ? `<p>${esc(node.description)}</p>` : ""}
      <div class="graph-metrics">
        <span><strong>${esc(node.degree)}</strong>连接</span>
        <span><strong>${esc(node.inbound)}</strong>入链</span>
        <span><strong>${esc(node.outbound)}</strong>出链</span>
      </div>
      ${tags ? `<div class="tags">${tags}</div>` : ""}
      <h3>指向它的页面</h3>
      ${renderNodeList(inbound)}
      <h3>它指向的页面</h3>
      ${renderNodeList(outbound)}
    `;
  }

  function renderNodeList(nodes) {
    if (!nodes.length) return '<p class="graph-empty">当前筛选范围内没有关系。</p>';
    return `<div class="graph-link-list">${nodes
      .slice(0, 12)
      .map((item) => `<a href="${esc(item.href)}">${esc(item.title)}<span>${esc(item.category_label)} · ${esc(item.degree)}</span></a>`)
      .join("")}</div>`;
  }

  function render(options = {}) {
    const current = getVisibleData();
    visibleNodes = current.nodes;
    visibleEdges = current.edges;
    if (selectedId && !visibleNodes.some((node) => node.id === selectedId)) selectedId = null;
    runLayout(visibleNodes, visibleEdges);
    viewport.replaceChildren();

    for (const edge of visibleEdges) {
      const source = nodeById.get(edge.source);
      const target = nodeById.get(edge.target);
      const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
      line.dataset.edge = "true";
      line.dataset.source = edge.source;
      line.dataset.target = edge.target;
      line.classList.add("graph-edge");
      if (edge.kind === "related") line.classList.add("is-related");
      const cls = edgeClass(edge);
      if (cls) line.classList.add(cls);
      line.setAttribute("x1", source.x);
      line.setAttribute("y1", source.y);
      line.setAttribute("x2", target.x);
      line.setAttribute("y2", target.y);
      viewport.append(line);
    }

    const connected = new Set();
    if (selectedId || highlightedId) {
      const active = selectedId || highlightedId;
      for (const edge of visibleEdges) {
        if (edge.source === active) connected.add(edge.target);
        if (edge.target === active) connected.add(edge.source);
      }
    }

    for (const node of visibleNodes) {
      const group = document.createElementNS("http://www.w3.org/2000/svg", "g");
      group.classList.add("graph-node");
      if (selectedId === node.id) group.classList.add("is-selected");
      if ((selectedId || highlightedId) && node.id !== (selectedId || highlightedId) && !connected.has(node.id)) {
        group.classList.add("is-dimmed");
      }
      group.dataset.node = node.id;
      group.setAttribute("transform", `translate(${node.x} ${node.y})`);
      group.setAttribute("tabindex", "0");
      group.setAttribute("role", "button");
      group.setAttribute("aria-label", node.title);

      const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
      circle.setAttribute("r", nodeRadius(node));
      circle.setAttribute("fill", colorByCategory[node.category] || "#82b4ff");
      group.append(circle);

      if (node.degree >= 8 || selectedId === node.id || highlightedId === node.id) {
        const label = document.createElementNS("http://www.w3.org/2000/svg", "text");
        label.setAttribute("x", nodeRadius(node) + 7);
        label.setAttribute("y", 4);
        label.textContent = shortLabel(node.title);
        group.append(label);
      }

      group.addEventListener("click", () => {
        selectedId = node.id;
        render();
      });
      group.addEventListener("dblclick", () => {
        window.location.href = node.href;
      });
      group.addEventListener("keydown", (event) => {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          selectedId = node.id;
          render();
        }
      });
      group.addEventListener("pointerdown", (event) => {
        drag = { node, x: event.clientX, y: event.clientY };
        group.setPointerCapture(event.pointerId);
        event.stopPropagation();
      });
      viewport.append(group);
    }

    drawPositions();
    totals.textContent = `${visibleNodes.length} 个页面 · ${visibleEdges.length} 条关系`;
    renderInspector(selectedId);
    if (options.fit) {
      fitView();
    } else {
      applyTransform();
    }
  }

  categoryButtons.forEach((button) => {
    button.addEventListener("click", () => {
      const category = button.dataset.graphCategory;
      if (activeCategories.has(category) && activeCategories.size > 1) {
        activeCategories.delete(category);
      } else {
        activeCategories.add(category);
      }
      button.classList.toggle("is-active", activeCategories.has(category));
      button.setAttribute("aria-pressed", activeCategories.has(category) ? "true" : "false");
      render({ fit: true });
    });
  });

  searchInput.addEventListener("input", () => render({ fit: true }));
  resetButton.addEventListener("click", () => {
    searchInput.value = "";
    selectedId = null;
    highlightedId = null;
    activeCategories.clear();
    categories.forEach((cat) => activeCategories.add(cat));
    categoryButtons.forEach((button) => {
      button.classList.add("is-active");
      button.setAttribute("aria-pressed", "true");
    });
    scale = 1;
    panX = 0;
    panY = 0;
    render({ fit: true });
  });

  focusButton.addEventListener("click", () => {
    focusMode = !focusMode;
    workbench.classList.toggle("is-focus", focusMode);
    focusButton.textContent = focusMode ? "显示详情" : "专注看图";
    focusButton.setAttribute("aria-pressed", focusMode ? "true" : "false");
    window.requestAnimationFrame(() => render({ fit: true }));
  });

  zoomInButton.addEventListener("click", () => zoomBy(1.18));
  zoomOutButton.addEventListener("click", () => zoomBy(0.84));
  fitButton.addEventListener("click", fitView);

  svg.addEventListener("pointerdown", (event) => {
    if (event.target !== svg) return;
    panning = { x: event.clientX, y: event.clientY, panX, panY };
    svg.setPointerCapture(event.pointerId);
  });
  svg.addEventListener("pointermove", (event) => {
    if (drag) {
      const dx = (event.clientX - drag.x) / scale;
      const dy = (event.clientY - drag.y) / scale;
      drag.node.x += dx;
      drag.node.y += dy;
      drag.x = event.clientX;
      drag.y = event.clientY;
      drawPositions();
    } else if (panning) {
      panX = panning.panX + event.clientX - panning.x;
      panY = panning.panY + event.clientY - panning.y;
      applyTransform();
    }
  });
  svg.addEventListener("pointerup", () => {
    drag = null;
    panning = null;
  });
  svg.addEventListener("pointercancel", () => {
    drag = null;
    panning = null;
  });
  svg.addEventListener("wheel", (event) => {
    event.preventDefault();
    const rect = svg.getBoundingClientRect();
    const px = event.clientX - rect.left;
    const py = event.clientY - rect.top;
    const nextScale = Math.min(2.8, Math.max(0.42, scale * (event.deltaY > 0 ? 0.92 : 1.08)));
    panX = px - (px - panX) * (nextScale / scale);
    panY = py - (py - panY) * (nextScale / scale);
    scale = nextScale;
    applyTransform();
  }, { passive: false });

  workbench.classList.add("is-focus");
  focusButton.textContent = "显示详情";
  focusButton.setAttribute("aria-pressed", "true");
  render({ fit: true });
})();
"""


def build_graph_page(graph_data: dict[str, object]) -> str:
    graph_json = escape_script_json(json.dumps(graph_data, ensure_ascii=False, separators=(",", ":")))
    category_buttons = "".join(
        f'<button type="button" class="graph-filter is-active" data-graph-category="{esc(cat["id"])}" aria-pressed="true">'
        f'<span class="graph-filter-dot graph-filter-{esc(cat["id"])}"></span>{esc(cat["label"])}<small>{esc(cat["count"])}</small></button>'
        for cat in graph_data["categories"]
    )
    return f"""<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>知识图谱 · llm-wiki</title>
  <link rel="stylesheet" href="{ASSETS_REL}" />
{AUTO_MARKER}
</head>
<body>

<header class="topbar">
  <a class="brand" href="./index.html"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">知识图谱</span>
  <span class="spacer"></span>
  <span class="meta"><a href="./log.html">操作时间线 →</a></span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<main class="graph-page">
  <section class="graph-header">
    <div>
      <h1>知识图谱</h1>
      <p class="subtitle">从所有 wiki 页面中的 <code>[[wikilink]]</code> 和 frontmatter <code>related</code> 自动生成，用来快速看项目、实体和概念之间的连接。</p>
    </div>
    <a class="button-link" href="./index.html">返回索引</a>
  </section>

  <section class="graph-toolbar" aria-label="图谱筛选">
    <label class="sr-only" for="graph-search">搜索页面、标签、分类和描述</label>
    <input id="graph-search" type="search" placeholder="搜索项目、概念、标签" autocomplete="off" />
    <div class="graph-filters" aria-label="分类过滤">
      {category_buttons}
    </div>
    <button id="graph-focus" type="button" aria-pressed="true">显示详情</button>
    <button id="graph-reset" type="button">重置</button>
  </section>

  <section class="graph-workbench">
    <div class="graph-canvas-wrap">
      <div class="graph-canvas-head">
        <span id="graph-totals"></span>
        <div class="graph-canvas-actions" aria-label="图谱视图控制">
          <button id="graph-zoom-out" type="button" aria-label="缩小">−</button>
          <button id="graph-fit" type="button">适配</button>
          <button id="graph-zoom-in" type="button" aria-label="放大">＋</button>
        </div>
      </div>
      <svg id="knowledge-graph" role="img" aria-label="llm-wiki 页面关系图">
        <g id="graph-viewport"></g>
      </svg>
    </div>
    <aside id="graph-inspector" class="graph-inspector" aria-live="polite"></aside>
  </section>
</main>

<script type="application/json" id="graph-data">{graph_json}</script>
<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});
</script>
<script>{GRAPH_PAGE_SCRIPT}</script>

</body>
</html>
"""


def build_site_index(
    resolver: Resolver,
    body_html: str | None = None,
    descriptions: dict[str, str] | None = None,
) -> str:
    """Generate wiki/html/index.html — mirrors wiki/index.md structure with search."""
    if body_html is None or descriptions is None:
        body_html, descriptions = collect_index_descriptions(resolver)

    # All pages for search index
    pages = collect_page_meta(descriptions)
    topic_groups = build_topic_groups(pages)
    site_stats = build_site_stats(pages)
    recent_updates = parse_recent_updates()
    search_index = [
        {
            "title": p.title,
            "href": p.href,
            "category": p.category,
            "categoryLabel": p.category_label,
            "tags": p.tags,
            "description": p.description,
            "date": p.date,
        }
        for p in pages
    ]
    search_json = escape_script_json(json.dumps(search_index, ensure_ascii=False))

    extra_head = ""

    extra_body = f"""
<section class="home-hero">
  <div>
    <h1>llm-wiki</h1>
    <p class="subtitle">个人 LLM / AI Agent / 云原生 / 推理基础设施知识库。</p>
    <div class="home-actions">
      <a class="button-link" href="./graph.html">打开知识图谱</a>
      <a class="button-link button-link-secondary" href="./log.html">查看操作时间线</a>
    </div>
  </div>
  {render_stat_strip(site_stats)}
</section>

<section class="home-search">
  <label class="sr-only" for="search-input">搜索全站标题、标签、分类和描述</label>
  <input id="search-input" type="search" placeholder="搜索标题、标签、主题、项目" autocomplete="off" />
  <ul id="search-results"></ul>
</section>

<section class="home-section">
  <h2>主题入口</h2>
  {render_topic_grid(topic_groups)}
</section>

<div class="home-panels">
  {render_reading_paths(topic_groups)}
  {render_recent_updates(recent_updates)}
</div>

<script>
  const SEARCH_INDEX = {search_json};
  const input = document.getElementById("search-input");
  const out = document.getElementById("search-results");
  function search(q) {{
    q = q.trim().toLowerCase();
    if (!q) {{ out.replaceChildren(); return; }}
    const hits = SEARCH_INDEX.filter(e => {{
      const tags = (e.tags || []).join(" ");
      return [e.title, e.category, e.categoryLabel, tags, e.description]
        .join(" ")
        .toLowerCase()
        .includes(q);
    }}).slice(0, 30);
    const nodes = [];
    for (const e of hits) {{
      const li = document.createElement("li");
      const link = document.createElement("a");
      link.className = "wikilink";
      link.setAttribute("href", e.href);
      link.textContent = e.title;
      const meta = document.createElement("small");
      const tags = (e.tags || []).slice(0, 4).join(", ");
      meta.textContent = `${{e.categoryLabel}} · ${{tags}}`;
      li.append(link, meta);
      if (e.description) {{
        const description = document.createElement("p");
        description.textContent = e.description;
        li.append(description);
      }}
      nodes.push(li);
    }}
    out.replaceChildren(...nodes);
  }}
  input.addEventListener("input", e => search(e.target.value));
</script>

<section class="full-index" id="full-index">
  <h2>完整索引</h2>
  {body_html}
</section>
"""

    page_html = f"""<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>llm-wiki · 知识库索引</title>
  <link rel="stylesheet" href="{ASSETS_REL}" />
{extra_head}
{AUTO_MARKER}
</head>
<body>

<header class="topbar">
  <a class="brand" href="./index.html"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">全站首页</span>
  <span class="spacer"></span>
  <span class="meta"><a href="./graph.html">知识图谱 →</a></span>
  <span class="meta"><a href="./log.html">操作时间线 →</a></span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<div class="layout">
  <main class="content">

  {extra_body}

  <div class="footer">
    🦊 llm-wiki · 由 <code>wiki/html-assets/build.py</code> 自动生成
  </div>
  </main>
</div>

<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});
</script>

</body>
</html>
"""
    return page_html


# ── Driver ───────────────────────────────────────────────────────
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="Overwrite hand-crafted HTML too")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    resolver = Resolver()
    OUT.mkdir(parents=True, exist_ok=True)
    sync_html_assets(args.dry_run)
    index_body_html, descriptions = collect_index_descriptions(resolver)
    graph_data = collect_graph_data(resolver, descriptions)

    stats = {"written": 0, "skipped": 0, "total": 0}

    # Category pages
    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        dst_dir = OUT / cat
        dst_dir.mkdir(parents=True, exist_ok=True)
        for md_path in sorted(src_dir.glob("*.md")):
            page = load_page(md_path, cat)
            html = build_page(page, resolver, graph_data)
            dst = dst_dir / f"{md_path.stem}.html"
            stats["total"] += 1
            if not should_write(dst, args.force):
                normalize_stylesheet_href(dst, args.dry_run)
                stats["skipped"] += 1
                print(f"  skip (hand-crafted): {dst.relative_to(ROOT)}")
                continue
            if args.dry_run:
                print(f"  would write: {dst.relative_to(ROOT)}")
            else:
                dst.write_text(html, encoding="utf-8")
                stats["written"] += 1
                print(f"  ✓ {dst.relative_to(ROOT)}")

    # log.md → log.html
    log_md = WIKI / "log.md"
    if log_md.exists():
        page = load_page(log_md, "ROOT")
        html = build_page(page, resolver, graph_data)
        dst = OUT / "log.html"
        stats["total"] += 1
        if should_write(dst, args.force):
            if not args.dry_run:
                dst.write_text(html, encoding="utf-8")
            stats["written"] += 1
            print(f"  ✓ {dst.relative_to(ROOT)}")
        else:
            stats["skipped"] += 1

    # Site index
    dst = OUT / "index.html"
    stats["total"] += 1
    if should_write(dst, args.force):
        html = build_site_index(resolver, index_body_html, descriptions)
        if not args.dry_run:
            dst.write_text(html, encoding="utf-8")
        stats["written"] += 1
        print(f"  ✓ {dst.relative_to(ROOT)}")
    else:
        stats["skipped"] += 1

    # Knowledge graph
    graph_json_dst = OUT / "graph.json"
    if args.dry_run:
        print(f"  would write: {graph_json_dst.relative_to(ROOT)}")
    else:
        graph_json_dst.write_text(json.dumps(graph_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"  ✓ {graph_json_dst.relative_to(ROOT)}")

    dst = OUT / "graph.html"
    stats["total"] += 1
    if should_write(dst, args.force):
        html = build_graph_page(graph_data)
        if args.dry_run:
            print(f"  would write: {dst.relative_to(ROOT)}")
        else:
            dst.write_text(html, encoding="utf-8")
            print(f"  ✓ {dst.relative_to(ROOT)}")
        stats["written"] += 1
    else:
        stats["skipped"] += 1

    print(
        f"\nDone. wrote {stats['written']} · skipped {stats['skipped']} (hand-crafted) · total {stats['total']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
