#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["markdown==3.10.2", "pypdf==6.19.0"]
# ///
"""
llm-wiki HTML builder.

Walks wiki/{entities,concepts,sources,analysis}/*.md + wiki/{index,log}.md and
generates a mirrored tree under wiki/html/ using the shared style.css.

Hand-crafted HTML pages (e.g. wiki/html/sources/src-nanobot-architecture.html
with Mermaid diagrams) are preserved: build.py only overwrites files that
either don't exist or carry the auto-generated marker.

Run: ./wiki/html-assets/build.py            (idempotent)
     ./wiki/html-assets/build.py --force    (overwrite everything)
"""
from __future__ import annotations

import argparse
import html as htmllib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable, Iterator
from urllib.parse import unquote, urlsplit
from dataclasses import dataclass, field
from datetime import date
from html.parser import HTMLParser
from pathlib import Path

import markdown as md
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent.parent
WIKI = ROOT / "wiki"
OUT = WIKI / "html"
PDF_OUT = OUT / "pdf"
ASSETS_REL = "html-assets/style.css"

AUTO_MARKER = "<!-- generated by wiki/html-assets/build.py -->"
STYLESHEET_RE = re.compile(r'href="(?:\.\./)*html-assets/style\.css"')
MERMAID_VERSION = "10.9.0"
MERMAID_BLOCK_RE = re.compile(r'<pre><code class="language-mermaid">(.*?)</code></pre>', re.DOTALL)

CATEGORIES = ("entities", "concepts", "sources", "analysis")
CATEGORY_LABELS = {
    "entities": "实体",
    "concepts": "概念",
    "sources": "源文件",
    "analysis": "分析",
}

TOPIC_GROUPS = [
    {
        "slug": "ai-agent-memory",
        "title": "AI Agent / Memory",
        "description": "长期记忆、MCP、coding agent、Agent framework 与个人 AI 工具链。",
        "tags": {"agent-memory", "ai-agent", "mcp", "claude-code", "agent-framework"},
        "preferred": (
            "agent-memory-project-map",
            "ai-agent-frameworks-map",
            "agent-memory",
            "claude-code",
        ),
    },
    {
        "slug": "agent-runtime-sandbox",
        "title": "Agent Runtime / Sandbox",
        "description": "Agent 会话编排、沙箱隔离、凭据托管、网关治理和多 Agent 协作。",
        "tags": {"agent-runtime", "agent-sandbox", "sandbox", "multi-agent", "ai-gateway"},
        "preferred": (
            "agent-runtime-sandbox-project-map",
            "agent-sandbox",
            "openkruise-agents",
            "agentgateway",
        ),
    },
    {
        "slug": "llm-inference-serving",
        "title": "LLM Inference / Serving",
        "description": "推理服务、KV cache、PagedAttention、RadixAttention 和多云 GPU 编排。",
        "tags": {"llm-inference", "llm-serving", "kv-cache", "ai-infra", "gpu"},
        "preferred": (
            "llm-inference-serving-project-map",
            "llm-inference",
            "paged-attention",
            "radix-attention",
        ),
    },
    {
        "slug": "kubernetes-cloud-native",
        "title": "Kubernetes / Cloud Native",
        "description": "Kubernetes、KEP 设计追踪、GitOps、controller/operator、GPU 资源栈、安全和可观测。",
        "tags": {"kubernetes", "cloud-native", "gitops", "controller", "operator", "kep"},
        "preferred": (
            "kubernetes-keps-feature-coverage",
            "kubernetes-keps-implementation-matrix",
            "kubernetes-keps-design-tracking",
            "kubernetes",
        ),
    },
]

READING_PATHS = [
    {
        "title": "Agent Memory 入门",
        "description": "先理解长期记忆问题，再看项目地图和代表实现。",
        "steps": (
            ("概念", "agent-memory"),
            ("地图", "agent-memory-project-map"),
            ("选型", "agent-memory-selection-matrix"),
        ),
    },
    {
        "title": "Agent Runtime / Sandbox",
        "description": "从运行时隔离、会话编排到凭据和网关治理。",
        "steps": (
            ("地图", "agent-runtime-sandbox-project-map"),
            ("原语", "agent-sandbox"),
            ("平台", "openkruise-agents"),
            ("治理", "agent-credential-isolation"),
        ),
    },
    {
        "title": "Coding Agent 选型",
        "description": "对比本地 CLI、插件、托管 teammate 和观测工具。",
        "steps": (
            ("地图", "coding-agent-selection-map"),
            ("基线", "codex"),
            ("协作", "multica"),
        ),
    },
    {
        "title": "LLM Serving / Inference",
        "description": "从请求与调度，经 P/D、路由、性能和可靠性，走到项目组合与选型。",
        "steps": (
            ("基础", "llm-inference"),
            ("调度", "continuous-batching"),
            ("分布式", "disaggregated-serving"),
            ("路由", "inference-routing"),
            ("性能", "llm-serving-performance"),
            ("可靠性", "llm-serving-reliability"),
            ("地图", "llm-inference-serving-project-map"),
            ("选型", "llm-serving-engine-selection-map"),
        ),
    },
    {
        "title": "AI Gateway / Routing",
        "description": "理解模型网关、MCP 工具网关、推理路由和 provider 治理。",
        "steps": (
            ("概念", "ai-gateway"),
            ("地图", "mcp-gateway-tooling-map"),
            ("样本", "agentgateway"),
        ),
    },
    {
        "title": "K8s GPU / Device Stack",
        "description": "从 device plugin、GPU Operator、DRA/CDI 到 GPU sharing。",
        "steps": (
            ("地图", "k8s-gpu-device-stack"),
            ("机制", "kubernetes-dra"),
            ("实现", "hami"),
        ),
    },
    {
        "title": "Kubernetes KEP 设计追踪",
        "description": "按 Scheduling、Autoscaling、Node 三个 SIG 看重要 KEP、合并 feature 和设计详解。",
        "steps": (
            ("覆盖", "kubernetes-keps-feature-coverage"),
            ("状态", "kubernetes-keps-implementation-matrix"),
            ("追踪", "kubernetes-keps-design-tracking"),
            ("调度", "kubernetes-scheduler-core-design"),
        ),
    },
    {
        "title": "Code Intelligence / Repo Wiki",
        "description": "对比语义检索、代码图谱、Graph RAG 和自动 repo wiki。",
        "steps": (
            ("地图", "code-semantic-search-rag-map"),
            ("图谱", "code-graph"),
            ("产品", "deepwiki-open"),
        ),
    },
    {
        "title": "中文 AI Infra 学习路线",
        "description": "把中文学习项目按 AI 系统、CUDA、推理、Agent 分层。",
        "steps": (
            ("路线", "ai-infra-learning-cn-map"),
            ("底稿", "src-ai-infra-learning-cn-stars"),
            ("总览", "github-stars-backlog-implementation-map"),
        ),
    },
]


# ── Frontmatter ──────────────────────────────────────────────────
FRONTMATTER_RE = re.compile(r"\A[^\n]*?---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass
class Frontmatter:
    title: str = ""
    tags: list[str] = field(default_factory=list)
    date: str = ""
    sources: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)


def parse_frontmatter(text: str) -> tuple[Frontmatter, str]:
    """Tolerant: accepts garbage chars before the first --- (e.g. kubernetes.md `k2---`)."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return Frontmatter(), text
    raw = m.group(1)
    body = text[m.end():]
    fm = Frontmatter()
    for line in raw.splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k, v = k.strip(), v.strip()
        if not v:
            continue
        if k == "title":
            fm.title = v.strip('"').strip("'")
        elif k == "date":
            fm.date = v.strip('"').strip("'")
        elif k in ("tags", "sources", "related"):
            items = re.findall(r"\[\[([^\]]+)\]\]|\"([^\"]+)\"|'([^']+)'|([^,\[\]\s]+)", v)
            flat = [a or b or c or d for (a, b, c, d) in items]
            flat = [x.strip().strip('"').strip("'").strip("[").strip("]") for x in flat if x]
            flat = [x for x in flat if x]
            setattr(fm, k, flat)
    return fm, body


# ── Wikilink resolution ──────────────────────────────────────────
class Resolver:
    """Index every wiki/*.md by stem → its category (entities/concepts/sources/analysis)."""

    def __init__(self) -> None:
        self.index: dict[str, str] = {}
        self.canonical: dict[str, str] = {}
        for cat in CATEGORIES:
            d = WIKI / cat
            if not d.is_dir():
                continue
            for f in d.glob("*.md"):
                self.index[f.stem] = cat
                self.index[f.stem.lower()] = cat
                self.canonical[f.stem] = f.stem
                self.canonical[f.stem.lower()] = f.stem

    def resolve(self, target: str) -> tuple[str, str] | None:
        """Return (category, canonical stem) for a target page; None if not found."""
        stem = target.strip()
        if "|" in stem:
            stem, _ = stem.split("|", 1)
        if "#" in stem:
            stem, _ = stem.split("#", 1)
        stem = stem.strip()
        if not stem:
            return None
        cat = self.index.get(stem) or self.index.get(stem.lower())
        if not cat:
            return None
        return cat, self.canonical.get(stem) or self.canonical.get(stem.lower()) or stem

    def href(self, target: str, *, from_cat: str | None) -> str | None:
        """Return relative href from a page in from_cat to target page; None if not found."""
        resolved = self.resolve(target)
        if not resolved:
            return None
        cat, real_stem = resolved
        target_path = f"{cat}/{real_stem}.html"
        _, separator, heading = target.split("|", 1)[0].partition("#")
        if separator:
            target_path += f"#{slugify(heading)}"
        if from_cat is None:
            return target_path  # called from wiki/html/index.html
        return f"../{target_path}"


@dataclass(frozen=True)
class NavigationItem:
    category: str
    stem: str
    title: str
    href: str


def reading_order(
    resolver: Resolver,
    index_md: str | None = None,
) -> list[tuple[str, str]]:
    """Return resolved wiki pages in first-seen order from wiki/index.md."""
    if index_md is None:
        index_md = (WIKI / "index.md").read_text(encoding="utf-8")

    order: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for raw in WIKILINK_RE.findall(index_md):
        resolved = resolver.resolve(raw)
        if resolved and resolved not in seen:
            seen.add(resolved)
            order.append(resolved)
    return order


def navigation_for(
    category: str,
    stem: str,
    resolver: Resolver,
    order: list[tuple[str, str]],
) -> tuple[NavigationItem | None, NavigationItem | None]:
    """Return the previous and next resolved pages for the current page."""
    current = (category, stem)
    try:
        index = order.index(current)
    except ValueError:
        return None, None

    previous = navigation_item_for(order[index - 1], resolver, category) if index > 0 else None
    following = (
        navigation_item_for(order[index + 1], resolver, category)
        if index + 1 < len(order)
        else None
    )
    return previous, following


def navigation_item_for(
    target: tuple[str, str],
    resolver: Resolver,
    from_cat: str | None,
) -> NavigationItem:
    target_category, target_stem = target
    target_page = load_page(WIKI / target_category / f"{target_stem}.md", target_category)
    href = resolver.href(target_stem, from_cat=from_cat)
    if href is None:
        raise ValueError(f"unresolved navigation target: {target_stem}")
    return NavigationItem(target_category, target_stem, target_page.title, href)


# ── Wikilink preprocessing ───────────────────────────────────────
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
FENCE_OPEN_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")


def markdown_segments(body: str) -> Iterator[tuple[bool, str]]:
    """Yield (is_fenced_code, original_text), preserving fences without placeholders."""
    chunk: list[str] = []
    closing: re.Pattern[str] | None = None
    for line in body.splitlines(keepends=True):
        content = line.rstrip("\r\n")
        if closing is not None:
            chunk.append(line)
            if closing.fullmatch(content):
                yield True, "".join(chunk)
                chunk = []
                closing = None
            continue

        opening = FENCE_OPEN_RE.match(content)
        if opening and not (opening[1][0] == "`" and "`" in opening[2]):
            if chunk:
                yield False, "".join(chunk)
            fence = opening[1]
            closing = re.compile(r" {0,3}" + re.escape(fence[0]) + "{" + str(len(fence)) + r",}[ \t]*")
            chunk = [line]
        else:
            chunk.append(line)
    if chunk:
        yield closing is not None, "".join(chunk)


def transform_outside_fenced_code(body: str, transform: Callable[[str], str]) -> str:
    """Apply transform to Markdown prose while preserving fenced code verbatim."""
    return "".join(
        text if fenced else transform(text)
        for fenced, text in markdown_segments(body)
    )


def transform_outside_inline_code(body: str, transform: Callable[[str], str]) -> str:
    """Apply transform outside matching Markdown backtick code spans."""
    output: list[str] = []
    cursor = 0
    while opening := re.search(r"`+", body[cursor:]):
        opening_start = cursor + opening.start()
        opening_end = cursor + opening.end()
        delimiter = opening.group(0)
        closing = re.search(
            rf"(?<!`){re.escape(delimiter)}(?!`)",
            body[opening_end:],
        )
        if closing is None:
            break
        closing_end = opening_end + closing.end()
        output.append(transform(body[cursor:opening_start]))
        output.append(body[opening_start:closing_end])
        cursor = closing_end
    output.append(transform(body[cursor:]))
    return "".join(output)


def rewrite_wikilinks(body: str, resolver: Resolver, from_cat: str | None) -> str:
    def repl(m: re.Match) -> str:
        target = m.group(1).strip()
        label = target
        if "|" in target:
            target, label = target.split("|", 1)
            target = target.strip()
            label = label.strip()
        href = resolver.href(target, from_cat=from_cat)
        if href:
            return f'<a class="wikilink" href="{href}">{htmllib.escape(label)}</a>'
        return f'<span class="wikilink wikilink-missing" title="未建页：{htmllib.escape(target)}">{htmllib.escape(label)}</span>'

    return "".join(text if fenced else WIKILINK_RE.sub(repl, text) for fenced, text in markdown_segments(body))


def page_anchor(stem: str) -> str:
    return f"page-{slugify(stem)}"


def rewrite_topic_wikilinks(body: str, resolver: Resolver, included: set[str]) -> str:
    """Rewrite wiki links for a self-contained book without local HTML links."""
    included_lower = {stem.lower() for stem in included}

    def repl(m: re.Match) -> str:
        raw_target = m.group(1).strip()
        target_with_fragment = raw_target
        label: str | None = None
        if "|" in target_with_fragment:
            target_with_fragment, label = target_with_fragment.split("|", 1)
            target_with_fragment = target_with_fragment.strip()
            label = label.strip()

        target, separator, fragment = target_with_fragment.partition("#")
        target = target.strip()
        fragment = fragment.strip()
        readable = label or target
        readable = htmllib.escape(readable).replace("[", "\\[").replace("]", "\\]")
        resolved = resolver.resolve(target)
        if resolved:
            _category, stem = resolved
            if stem.lower() in included_lower:
                anchor = page_anchor(stem)
                if separator and fragment:
                    anchor = f"{anchor}--{slugify(fragment)}"
                return f"[{readable}](#{anchor})"
        return readable

    return transform_outside_fenced_code(
        body,
        lambda prose: transform_outside_inline_code(
            prose,
            lambda text: WIKILINK_RE.sub(repl, text),
        ),
    )


def rewrite_topic_image_destinations(body: str, source_dir: Path) -> str:
    """Resolve page-relative Markdown images for the temporary topic book."""

    def unescape_destination(destination: str) -> str:
        punctuation = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
        output: list[str] = []
        cursor = 0
        while cursor < len(destination):
            if (
                destination[cursor] == "\\"
                and cursor + 1 < len(destination)
                and destination[cursor + 1] in punctuation
            ):
                cursor += 1
            output.append(destination[cursor])
            cursor += 1
        return "".join(output)

    def resolve_destination(raw_destination: str) -> str:
        destination = unescape_destination(raw_destination)
        parsed = urlsplit(destination)
        if destination.startswith("#") or parsed.scheme or parsed.netloc:
            return raw_destination

        absolute_uri = (source_dir / unquote(parsed.path)).resolve().as_uri()
        if parsed.query:
            absolute_uri += f"?{parsed.query}"
        if parsed.fragment:
            absolute_uri += f"#{parsed.fragment}"
        return absolute_uri

    def destination_span(text: str, start: int) -> tuple[int, int, int] | None:
        cursor = start + 2
        bracket_depth = 0
        while cursor < len(text):
            char = text[cursor]
            if char == "\\" and cursor + 1 < len(text):
                cursor += 2
                continue
            if char == "[":
                bracket_depth += 1
            elif char == "]":
                if bracket_depth == 0:
                    break
                bracket_depth -= 1
            cursor += 1
        if cursor + 1 >= len(text) or text[cursor + 1] != "(":
            return None

        cursor += 2
        while cursor < len(text) and text[cursor] in " \t":
            cursor += 1
        angled = cursor < len(text) and text[cursor] == "<"
        if angled:
            destination_start = cursor + 1
            cursor = destination_start
            while cursor < len(text):
                if text[cursor] == "\\" and cursor + 1 < len(text):
                    cursor += 2
                    continue
                if text[cursor] == ">":
                    break
                if text[cursor] == "\n":
                    return None
                cursor += 1
            if cursor >= len(text):
                return None
            destination_end = cursor
            cursor += 1
        else:
            destination_start = cursor
            parenthesis_depth = 0
            while cursor < len(text):
                char = text[cursor]
                if char == "\\" and cursor + 1 < len(text):
                    cursor += 2
                    continue
                if char == "(":
                    parenthesis_depth += 1
                elif char == ")":
                    if parenthesis_depth == 0:
                        break
                    parenthesis_depth -= 1
                elif char in " \t" and parenthesis_depth == 0:
                    break
                elif char == "\n":
                    return None
                cursor += 1
            if cursor >= len(text) or parenthesis_depth != 0:
                return None
            destination_end = cursor

        title_separator = cursor
        while cursor < len(text) and text[cursor] in " \t":
            cursor += 1
        if cursor < len(text) and text[cursor] == ")":
            return destination_start, destination_end, cursor + 1
        if cursor == title_separator or cursor >= len(text):
            return None

        delimiter = text[cursor]
        if delimiter in "\"'":
            cursor += 1
            while cursor < len(text):
                if text[cursor] == "\\" and cursor + 1 < len(text):
                    cursor += 2
                    continue
                if text[cursor] == delimiter:
                    cursor += 1
                    break
                if text[cursor] == "\n":
                    return None
                cursor += 1
            else:
                return None
        elif delimiter == "(":
            title_depth = 1
            cursor += 1
            while cursor < len(text) and title_depth:
                if text[cursor] == "\\" and cursor + 1 < len(text):
                    cursor += 2
                    continue
                if text[cursor] == "(":
                    title_depth += 1
                elif text[cursor] == ")":
                    title_depth -= 1
                elif text[cursor] == "\n":
                    return None
                cursor += 1
            if title_depth:
                return None
        else:
            return None

        while cursor < len(text) and text[cursor] in " \t":
            cursor += 1
        if cursor >= len(text) or text[cursor] != ")":
            return None
        return destination_start, destination_end, cursor + 1

    def rewrite_prose(text: str) -> str:
        output: list[str] = []
        output_cursor = 0
        search_cursor = 0
        while (image_start := text.find("![", search_cursor)) >= 0:
            span = destination_span(text, image_start)
            if span is None:
                search_cursor = image_start + 2
                continue
            destination_start, destination_end, image_end = span
            output.append(text[output_cursor:destination_start])
            output.append(resolve_destination(text[destination_start:destination_end]))
            output_cursor = destination_end
            search_cursor = image_end
        output.append(text[output_cursor:])
        return "".join(output)

    return transform_outside_fenced_code(
        body,
        lambda prose: transform_outside_inline_code(
            prose,
            rewrite_prose,
        ),
    )


# ── TOC extraction ───────────────────────────────────────────────
HEADING_RE = re.compile(r"^(#{1,6})[ \t]+([^\r\n]+?)[ \t]*(?=\r?$)", re.MULTILINE)


def slugify(s: str) -> str:
    s = re.sub(r"[<>&\"']+", "", s)
    s = re.sub(r"\s+", "-", s.strip().lower())
    s = re.sub(r"[^a-z0-9\u4e00-\u9fa5\-_]", "", s)
    return s[:80] or "section"


def extract_toc(body: str) -> list[tuple[int, str, str]]:
    """Return [(level, text, slug)] for h2/h3 (skip h1; it's the page title)."""
    toc = []
    seen: dict[str, int] = {}
    headings = (
        match
        for fenced, text in markdown_segments(body)
        if not fenced
        for match in HEADING_RE.finditer(text)
    )
    for m in headings:
        hashes, text = m.group(1), m.group(2)
        level = len(hashes)
        if level < 2 or level > 3:
            continue
        slug = slugify(text)
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 1
        toc.append((level, text, slug))
    return toc


def inject_heading_ids(body: str, namespace: str | None = None) -> str:
    """Add {#slug} to h2/h3 so python-markdown's toc extension picks them up."""
    seen: dict[str, int] = {}

    def repl(m: re.Match) -> str:
        hashes, text = m.group(1), m.group(2)
        level = len(hashes)
        if level < 2 or level > 3:
            return m.group(0)
        # Strip wikilink syntax for slugification only
        plain = WIKILINK_RE.sub(r"\1", text)
        slug = slugify(plain)
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 1
        if namespace:
            slug = f"{namespace}--{slug}"
        return f"{hashes} {text} {{#{slug}}}"

    return transform_outside_fenced_code(body, lambda prose: HEADING_RE.sub(repl, prose))


# ── HTML shell ───────────────────────────────────────────────────
MERMAID_RUNTIME = """<script>
  let mermaidRenderInFlight = false;
  let mermaidRenderPending = false;

  function showMermaidError(figures, text) {
    figures.forEach((figure) => {
      const target = figure.querySelector(".mermaid");
      if (!target) return;
      figure.classList.remove("is-rendered");
      figure.querySelectorAll(".mermaid-error").forEach((error) => error.remove());
      target.hidden = true;
      target.setAttribute("aria-hidden", "true");
      const message = document.createElement("p");
      message.className = "mermaid-error";
      message.textContent = text;
      figure.appendChild(message);
    });
  }

  async function renderMermaidDiagrams() {
    if (mermaidRenderInFlight) {
      mermaidRenderPending = true;
      return;
    }

    const figures = Array.from(document.querySelectorAll(".mermaid-figure"));
    if (!figures.length || !window.mermaid) return;

    const theme = document.documentElement.getAttribute("data-theme") === "light"
      ? "default"
      : "dark";
    const nodes = [];
    const renderableFigures = [];
    figures.forEach((figure) => {
      const source = figure.querySelector(".mermaid-source");
      const target = figure.querySelector(".mermaid");
      if (!source || !target) return;

      figure.classList.remove("is-rendered");
      figure.querySelectorAll(".mermaid-error").forEach((error) => error.remove());
      target.removeAttribute("data-processed");
      target.replaceChildren(document.createTextNode(source.textContent || ""));
      target.hidden = false;
      target.setAttribute("aria-hidden", "false");
      nodes.push(target);
      renderableFigures.push(figure);
    });
    if (!nodes.length) return;

    mermaidRenderInFlight = true;
    try {
      window.mermaid.initialize({
        startOnLoad: false,
        theme,
        securityLevel: "strict",
        flowchart: { useMaxWidth: false },
        sequence: { useMaxWidth: false },
      });
      await window.mermaid.run({ nodes });
      renderableFigures.forEach((figure) => figure.classList.add("is-rendered"));
    } catch (error) {
      showMermaidError(renderableFigures, "图表渲染失败，以下保留 Mermaid 源码。");
      console.error("Mermaid diagram rendering failed", error);
    } finally {
      mermaidRenderInFlight = false;
      if (mermaidRenderPending) {
        mermaidRenderPending = false;
        renderMermaidDiagrams();
      }
    }
  }

  const mermaidLoader = document.getElementById("mermaid-loader");
  let mermaidLoadTimeout;
  function mermaidLoadFailed() {
    clearTimeout(mermaidLoadTimeout);
    if (window.mermaid) return;
    showMermaidError(
      Array.from(document.querySelectorAll(".mermaid-figure")),
      "图表组件加载失败或超时，以下保留 Mermaid 源码。"
    );
  }
  function mermaidLoaded() {
    clearTimeout(mermaidLoadTimeout);
    if (!window.mermaid) {
      mermaidLoadFailed();
      return;
    }
    renderMermaidDiagrams();
  }
  if (mermaidLoader) {
    mermaidLoader.addEventListener("load", mermaidLoaded);
    mermaidLoader.addEventListener("error", mermaidLoadFailed);
  }
  if (window.mermaid) {
    mermaidLoaded();
  } else {
    mermaidLoadTimeout = setTimeout(mermaidLoadFailed, 8000);
  }
  document.getElementById("theme-toggle").addEventListener("click", () => {
    renderMermaidDiagrams();
  });
</script>"""


SHELL = """<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title} · llm-wiki</title>
  <link rel="stylesheet" href="{style_href}" />
{extra_head}
{auto_marker}
</head>
<body>

<header class="topbar">
  <a class="brand" href="{home_href}"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">{breadcrumb}</span>
  <span class="spacer"></span>
  <span class="meta">{meta_right}</span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<div class="layout">
  <main class="content">

  <header class="page-header">
    <h1>{title}</h1>
    {subtitle_html}
    {tags_html}
  </header>

  {body_html}

  {navigation_html}

  <div class="footer">
    🦊 llm-wiki · {category_label} · <a href="{md_href}">查看 Markdown 源</a>
  </div>
  </main>

  {sidebar_html}
</div>

<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});

  const tocLinks = document.querySelectorAll(".toc a");
  const headings = Array.from(document.querySelectorAll("h2[id], h3[id]"));
  function updateActive() {{
    let active = headings[0];
    for (const h of headings) {{
      if (h.getBoundingClientRect().top - 100 <= 0) active = h;
    }}
    if (!active) return;
    tocLinks.forEach((a) =>
      a.classList.toggle("active", a.getAttribute("href") === "#" + active.id)
    );
  }}
  window.addEventListener("scroll", updateActive, {{ passive: true }});
  updateActive();
</script>
{extra_script}

</body>
</html>
"""


def render_toc(toc: list[tuple[int, str, str]]) -> str:
    if not toc:
        return ""
    items = []
    for level, text, slug in toc:
        # strip wikilink syntax for TOC label
        label = WIKILINK_RE.sub(r"\1", text)
        cls = "level-3" if level == 3 else ""
        items.append(f'<li class="{cls}"><a href="#{slug}">{htmllib.escape(label)}</a></li>')
    return (
        '<aside class="toc"><h4>本页目录</h4><ul>'
        + "".join(items)
        + "</ul></aside>"
    )


def graph_node_href(node: dict[str, object], from_cat: str | None) -> str:
    href = str(node["href"])
    if from_cat is None:
        return href
    return f"../{href}"


def render_page_relations(page: Page, graph_data: dict[str, object] | None) -> str:
    if not graph_data or page.category == "ROOT":
        return ""
    current_id = page.md_path.stem
    nodes = {str(node["id"]): node for node in graph_data["nodes"]}
    if current_id not in nodes:
        return ""

    inbound = [edge for edge in graph_data["edges"] if edge["target"] == current_id and edge["source"] in nodes]
    outbound = [edge for edge in graph_data["edges"] if edge["source"] == current_id and edge["target"] in nodes]
    neighbor_ids: list[str] = []
    for edge in outbound:
        target = str(edge["target"])
        if target not in neighbor_ids:
            neighbor_ids.append(target)
    for edge in inbound:
        source = str(edge["source"])
        if source not in neighbor_ids:
            neighbor_ids.append(source)

    neighbors = [nodes[node_id] for node_id in neighbor_ids[:12]]
    mini_nodes = neighbors[:8]
    graph_href = f"../graph.html?focus={htmllib.escape(current_id, quote=True)}"

    if mini_nodes:
        center_x = 120
        center_y = 82
        radius = 58
        lines = []
        circles = [
            '<circle class="mini-node mini-node-current" cx="120" cy="82" r="10" />',
            f'<text x="120" y="108" text-anchor="middle">{htmllib.escape(page.title[:16])}</text>',
        ]
        for index, node in enumerate(mini_nodes):
            angle = (index / max(len(mini_nodes), 1)) * 6.28318 - 1.5708
            x = center_x + radius * math.cos(angle)
            y = center_y + radius * math.sin(angle)
            category = htmllib.escape(str(node["category"]), quote=True)
            lines.append(f'<line x1="{center_x:.1f}" y1="{center_y:.1f}" x2="{x:.1f}" y2="{y:.1f}" />')
            circles.append(
                f'<circle class="mini-node mini-node-{category}" cx="{x:.1f}" cy="{y:.1f}" r="7">'
                f'<title>{htmllib.escape(str(node["title"]))}</title></circle>'
            )
        mini_svg = (
            '<svg class="mini-graph" viewBox="0 0 240 150" role="img" aria-label="本页一跳关系图">'
            + "".join(lines)
            + "".join(circles)
            + "</svg>"
        )
    else:
        mini_svg = '<p class="side-empty">本页还没有可解析的 wiki 关系。</p>'

    def render_items(edges: list[dict[str, str]], direction: str) -> str:
        if not edges:
            return '<p class="side-empty">暂无。</p>'
        items = []
        for edge in edges[:8]:
            node_id = edge["source"] if direction == "in" else edge["target"]
            node = nodes.get(node_id)
            if not node:
                continue
            items.append(
                '<li>'
                f'<a href="{graph_node_href(node, page.category)}">{htmllib.escape(str(node["title"]))}</a>'
                f'<span>{htmllib.escape(str(node["category_label"]))} · {htmllib.escape(str(edge["kind"]))}</span>'
                '</li>'
            )
        return f'<ul class="side-link-list">{"".join(items)}</ul>' if items else '<p class="side-empty">暂无。</p>'

    return (
        '<aside class="side-panel page-relations">'
        '<div class="side-panel-head"><h3>关系图谱</h3>'
        f'<a href="{graph_href}">全局打开</a></div>'
        f'{mini_svg}'
        '<h4>它指向</h4>'
        f'{render_items(outbound, "out")}'
        '<h4>反向链接</h4>'
        f'{render_items(inbound, "in")}'
        '</aside>'
    )


def render_sidebar(toc_html: str, relation_html: str) -> str:
    if not toc_html and not relation_html:
        return ""
    return f'<aside class="right-rail">{relation_html}{toc_html}</aside>'


def render_tags(tags: list[str]) -> str:
    if not tags:
        return ""
    chips = "".join(f'<span class="tag">{htmllib.escape(t)}</span>' for t in tags)
    return f'<div class="tags">{chips}</div>'


def render_related(items: list[str], resolver: Resolver, from_cat: str | None) -> str:
    if not items:
        return ""
    lis = []
    for raw in items:
        target = raw.strip().strip("[").strip("]").strip()
        if not target:
            continue
        href = resolver.href(target, from_cat=from_cat)
        if href:
            lis.append(f'<li><a class="wikilink" href="{href}">{htmllib.escape(target)}</a></li>')
        else:
            lis.append(
                f'<li><span class="wikilink wikilink-missing" title="未建页：{htmllib.escape(target)}">'
                f'{htmllib.escape(target)}</span></li>'
            )
    return (
        '<section class="related-panel" aria-labelledby="related-frontmatter">'
        '<h2 id="related-frontmatter">相关页面</h2>'
        f'<ul>{"".join(lis)}</ul>'
        '</section>'
    )


def render_subtitle(fm: Frontmatter) -> str:
    parts = []
    if fm.date:
        parts.append(htmllib.escape(fm.date))
    if fm.sources:
        srcs = "、".join(htmllib.escape(s) for s in fm.sources)
        parts.append(f"来源：{srcs}")
    if not parts:
        return ""
    return f'<p class="page-meta">{" · ".join(parts)}</p>'


# ── Page builder ─────────────────────────────────────────────────
@dataclass
class Page:
    md_path: Path
    category: str  # entities / concepts / sources / analysis / ROOT (for index/log)
    fm: Frontmatter
    body_md: str
    title: str


@dataclass
class PageMeta:
    title: str
    href: str
    category: str
    category_label: str
    stem: str
    tags: list[str]
    date: str
    description: str = ""


@dataclass
class GraphNode:
    id: str
    title: str
    category: str
    category_label: str
    href: str
    tags: list[str]
    date: str
    description: str
    degree: int = 0
    inbound: int = 0
    outbound: int = 0


@dataclass(frozen=True)
class GraphEdge:
    source: str
    target: str
    kind: str


RELATED_SECTION_RE = re.compile(r"^##\s+相关页面\s*$.*?(?=^##\s+|\Z)", re.MULTILINE | re.DOTALL)


def render_mermaid_blocks(body_html: str) -> tuple[str, bool]:
    """Replace Markdown Mermaid code fences with renderable figure containers."""
    found = False

    def replace(match: re.Match[str]) -> str:
        nonlocal found
        found = True
        source = match.group(1)
        return (
            '<figure class="mermaid-figure">'
            '<pre class="mermaid-source" aria-label="Mermaid diagram source">'
            f"<code>{source}</code>"
            '</pre><div class="mermaid" hidden aria-hidden="true"></div></figure>'
        )

    return MERMAID_BLOCK_RE.sub(replace, body_html), found


def strip_markdown_related_section(body: str) -> str:
    """Use frontmatter related links as the single generated related panel."""
    return RELATED_SECTION_RE.sub("", body).rstrip() + "\n"


def build_page(
    page: Page,
    resolver: Resolver,
    graph_data: dict[str, object] | None = None,
    order: list[tuple[str, str]] | None = None,
) -> str:
    body_md = strip_markdown_related_section(page.body_md) if page.fm.related else page.body_md
    body_with_ids = inject_heading_ids(body_md)
    body_with_links = rewrite_wikilinks(body_with_ids, resolver, from_cat=page.category if page.category != "ROOT" else None)

    # Markdown → HTML
    converter = md.Markdown(
        extensions=["fenced_code", "tables", "attr_list", "admonition", "sane_lists", "nl2br"],
        output_format="html5",
    )
    body_html = converter.convert(body_with_links)

    # Drop the first <h1> if present; we render our own
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)
    body_html = re.sub(r"(<table>.*?</table>)", r'<div class="table-wrap">\1</div>', body_html, flags=re.DOTALL)
    body_html, has_mermaid = render_mermaid_blocks(body_html)

    toc = extract_toc(body_md)
    toc_html = render_toc(toc)
    relation_html = render_page_relations(page, graph_data)
    sidebar_html = render_sidebar(toc_html, relation_html)
    related_html = render_related(page.fm.related, resolver, from_cat=page.category if page.category != "ROOT" else None)
    navigation_html = render_navigation(page, resolver, order or [], related_html)

    is_root = page.category == "ROOT"
    style_href = ASSETS_REL if is_root else f"../{ASSETS_REL}"
    home_href = "./index.html" if is_root else "../index.html"
    md_href = f"../{page.md_path.name}" if is_root else f"../../{page.category}/{page.md_path.name}"
    breadcrumb = "wiki" if is_root else f"wiki · {page.category}"
    meta_right = page.fm.date or ""
    category_label = "ROOT" if is_root else page.category
    extra_head = (
        f'  <script id="mermaid-loader" defer src="https://cdn.jsdelivr.net/npm/mermaid@{MERMAID_VERSION}/dist/mermaid.min.js"></script>'
        if has_mermaid
        else ""
    )

    return SHELL.format(
        title=htmllib.escape(page.title),
        style_href=style_href,
        extra_head=extra_head,
        extra_script=MERMAID_RUNTIME if has_mermaid else "",
        auto_marker=AUTO_MARKER,
        home_href=home_href,
        breadcrumb=htmllib.escape(breadcrumb),
        meta_right=htmllib.escape(meta_right),
        subtitle_html=render_subtitle(page.fm),
        tags_html=render_tags(page.fm.tags),
        body_html=body_html,
        navigation_html=navigation_html,
        category_label=category_label,
        md_href=md_href,
        sidebar_html=sidebar_html,
    )


def load_page(md_path: Path, category: str) -> Page:
    text = md_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    # Title: frontmatter title > first h1 > filename
    title = fm.title
    if not title:
        h1 = re.search(r"^#\s+(.+?)\s*$", body, re.MULTILINE)
        title = h1.group(1).strip() if h1 else md_path.stem
    return Page(md_path=md_path, category=category, fm=fm, body_md=body, title=title)


def render_topic_chapter(page: Page, resolver: Resolver, included: set[str]) -> str:
    body_with_ids = inject_heading_ids(page.body_md, namespace=page_anchor(page.md_path.stem))
    body_with_links = rewrite_topic_wikilinks(body_with_ids, resolver, included)
    body_with_images = rewrite_topic_image_destinations(body_with_links, page.md_path.parent)
    converter = md.Markdown(
        extensions=["fenced_code", "tables", "attr_list", "admonition", "sane_lists", "nl2br"],
        output_format="html5",
    )
    body_html = converter.convert(body_with_images)
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)
    anchor = htmllib.escape(page_anchor(page.md_path.stem), quote=True)
    title = htmllib.escape(page.title)
    return f'<article class="book-chapter" id="{anchor}"><h1>{title}</h1>{body_html}</article>'


def build_topic_book(
    group: dict[str, object],
    resolver: Resolver,
    generated_on: str | None = None,
) -> str:
    page_metas = group.get("pages")
    if not isinstance(page_metas, list) or not all(isinstance(page, PageMeta) for page in page_metas):
        raise TypeError("topic group pages must be a list of PageMeta objects")

    generated_on = date.today().isoformat() if generated_on is None else generated_on
    included = {page.stem for page in page_metas}
    pages = [
        load_page(WIKI / page.category / f"{page.stem}.md", page.category)
        for page in page_metas
    ]
    title = htmllib.escape(str(group.get("title", "")))
    description = htmllib.escape(str(group.get("description", "")))
    generated = htmllib.escape(generated_on)
    stylesheet = htmllib.escape(
        (WIKI / "html-assets" / "topic-pdf.css").resolve().as_uri(),
        quote=True,
    )
    toc_items = "".join(
        f'<li><a href="#{htmllib.escape(page_anchor(page.md_path.stem), quote=True)}">'
        f'{htmllib.escape(page.title)}</a></li>'
        for page in pages
    )
    chapters = "".join(render_topic_chapter(page, resolver, included) for page in pages)
    for symbol in ("✅", "⚠", "❌"):
        chapters = chapters.replace(f"{symbol}\ufe0e", symbol)
        chapters = chapters.replace(f"{symbol}\ufe0f", symbol)
        chapters = chapters.replace(symbol, f"{symbol}\ufe0e")

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <title>{title}</title>
  <link rel="stylesheet" href="{stylesheet}" />
</head>
<body>
  <section class="book-cover">
    <h1>{title}</h1>
    <p class="book-description">{description}</p>
    <p class="book-meta">{len(pages)} 篇 · {generated}</p>
  </section>
  <nav class="book-toc" aria-label="目录">
    <h1>目录</h1>
    <ol>{toc_items}</ol>
  </nav>
  <main>{chapters}</main>
</body>
</html>
"""


def export_topic_pdf(
    group: dict[str, object],
    resolver: Resolver,
    output_dir: Path = PDF_OUT,
    renderer: str | None = None,
    timeout: float = 300,
) -> Path:
    renderer = renderer or shutil.which("weasyprint")
    if renderer is None:
        raise RuntimeError("WeasyPrint is required for PDF export")

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{group['slug']}.pdf"
    staging_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            prefix=f".{group['slug']}.",
            suffix=".pdf.tmp",
            dir=output_dir,
            delete=False,
        ) as staging_file:
            staging_path = Path(staging_file.name)

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            html_path = temp_path / "book.html"
            cache_path = temp_path / "cache"
            cache_path.mkdir()
            html_path.write_text(build_topic_book(group, resolver), encoding="utf-8")
            env = os.environ.copy()
            env["XDG_CACHE_HOME"] = os.fspath(cache_path)
            try:
                subprocess.run(
                    [renderer, os.fspath(html_path), os.fspath(staging_path)],
                    check=True,
                    env=env,
                    timeout=timeout,
                )
            except subprocess.TimeoutExpired as exc:
                raise RuntimeError(f"PDF renderer timed out after {timeout:g} seconds") from exc
            except OSError as exc:
                raise RuntimeError(f"Unable to run PDF renderer: {exc}") from exc

        if not is_complete_pdf(staging_path):
            raise RuntimeError(f"Renderer did not produce a valid PDF: {output_path}")
        try:
            staging_path.chmod(0o644)
            os.replace(staging_path, output_path)
        except OSError as exc:
            raise RuntimeError(f"Unable to publish PDF: {exc}") from exc
    finally:
        if staging_path is not None:
            staging_path.unlink(missing_ok=True)
    return output_path


def is_complete_pdf(path: Path) -> bool:
    try:
        reader = PdfReader(path, strict=True)
        if reader.is_encrypted:
            return False
        root = reader.trailer.get("/Root")
        if root is None or root.get("/Pages") is None:
            return False
        return len(reader.pages) > 0
    except Exception:
        return False


def render_root_navigation(
    resolver: Resolver,
    order: list[tuple[str, str]],
    *,
    include_return: bool,
    related_html: str = "",
) -> str:
    """Render navigation for root-level pages whose paths are relative to wiki/html/."""
    index_href = htmllib.escape("./index.html", quote=True)
    actions: list[str] = []
    if include_return:
        actions.append(
            f'<a class="page-navigation-link previous" href="{index_href}">'
            '<span class="navigation-label">← 返回索引</span></a>'
        )

    if order:
        first = navigation_item_for(order[0], resolver, None)
        href = htmllib.escape(first.href, quote=True)
        title = htmllib.escape(first.title)
        actions.append(
            f'<a class="page-navigation-link next recommended" href="{href}">'
            '<span class="navigation-label">推荐阅读第一篇 →</span>'
            f'<strong class="navigation-title">{title}</strong></a>'
        )

    if not actions and not related_html:
        return ""
    return (
        '<nav class="page-navigation" aria-label="页面阅读导航">'
        f'<div class="page-navigation-actions">{"".join(actions)}</div>'
        f'{related_html}</nav>'
    )


def render_navigation(
    page: Page,
    resolver: Resolver,
    order: list[tuple[str, str]],
    related_html: str = "",
) -> str:
    """Render navigation, owning the single related panel for this page."""
    if page.category == "ROOT":
        return render_root_navigation(
            resolver,
            order,
            include_return=page.md_path.name != "index.md",
            related_html=related_html,
        )

    previous, following = navigation_for(page.category, page.md_path.stem, resolver, order)
    index_href = htmllib.escape("../index.html", quote=True)

    if (page.category, page.md_path.stem) not in order:
        return (
            '<nav class="page-navigation" aria-label="页面阅读导航">'
            '<div class="page-navigation-actions">'
            f'<a class="page-navigation-index" href="{index_href}">返回索引</a>'
            f'</div>{related_html}</nav>'
        )

    def render_page_link(
        item: NavigationItem | None,
        class_name: str,
        label: str,
        boundary_label: str,
    ) -> str:
        if item is None:
            return (
                f'<a class="page-navigation-link {class_name} boundary" href="{index_href}">'
                f'<span class="navigation-label">{htmllib.escape(boundary_label)}</span></a>'
            )
        href = htmllib.escape(item.href, quote=True)
        title = htmllib.escape(item.title)
        return (
            f'<a class="page-navigation-link {class_name}" href="{href}">'
            f'<span class="navigation-label">{htmllib.escape(label)}</span>'
            f'<strong class="navigation-title">{title}</strong></a>'
        )

    position = None
    current = (page.category, page.md_path.stem)
    if current in order:
        position = order.index(current) + 1
    progress_html = (
        f'<span class="page-navigation-progress">阅读顺序 {position}/{len(order)}</span>'
        if position is not None
        else ""
    )

    return (
        '<nav class="page-navigation" aria-label="页面阅读导航">'
        '<div class="page-navigation-actions">'
        f'{render_page_link(previous, "previous", "← 上一页", "← 返回索引")}'
        f'<a class="page-navigation-index" href="{index_href}">返回索引</a>'
        f'{render_page_link(following, "next recommended", "推荐阅读下一页 →", "返回索引 →")}'
        f'</div>{progress_html}{related_html}</nav>'
    )


def should_write(dst: Path, force: bool) -> bool:
    if force or not dst.exists():
        return True
    head = dst.read_text(encoding="utf-8", errors="replace")[:2000]
    return AUTO_MARKER in head


def inject_navigation_into_handcrafted(dst: Path, navigation_html: str, dry_run: bool) -> bool:
    """Add navigation to preserved HTML without replacing its hand-crafted body."""
    if not dst.exists() or not navigation_html:
        return False
    text = dst.read_text(encoding="utf-8")
    if 'class="page-navigation"' in text:
        return False
    anchor = re.search(r"\n\s*<div class=\"footer\">", text)
    if not anchor:
        anchor = re.search(r"\n\s*</main>", text)
    if not anchor:
        anchor = re.search(r"\n\s*</body>", text)
    if not anchor:
        return False
    updated = text[:anchor.start()] + "\n\n" + navigation_html + text[anchor.start():]
    if not dry_run:
        dst.write_text(updated, encoding="utf-8")
    return True


def sync_html_assets(dry_run: bool) -> None:
    src = WIKI / "html-assets" / "style.css"
    dst = OUT / "html-assets" / "style.css"
    if dry_run:
        print(f"  would copy: {dst.relative_to(ROOT)}")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    print(f"  ✓ {dst.relative_to(ROOT)}")


def normalize_stylesheet_href(dst: Path, dry_run: bool) -> bool:
    if not dst.exists():
        return False
    style_href = Path(os.path.relpath(OUT / ASSETS_REL, dst.parent)).as_posix()
    text = dst.read_text(encoding="utf-8")
    next_text = STYLESHEET_RE.sub(f'href="{style_href}"', text)
    if next_text == text:
        return False
    if dry_run:
        print(f"  would update asset link: {dst.relative_to(ROOT)}")
        return True
    dst.write_text(next_text, encoding="utf-8")
    print(f"  ✓ asset link: {dst.relative_to(ROOT)}")
    return True


# ── Site index page ──────────────────────────────────────────────
class IndexDescriptionParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.descriptions: dict[str, str] = {}
        self._in_li = False
        self._href: str | None = None
        self._text_parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attrs_dict = dict(attrs)
        if tag == "li":
            self._in_li = True
            self._href = None
            self._text_parts = []
            return
        if tag == "a" and self._in_li and self._href is None:
            classes = (attrs_dict.get("class") or "").split()
            href = attrs_dict.get("href")
            if "wikilink" in classes and href:
                self._href = href

    def handle_data(self, data: str) -> None:
        if self._in_li:
            self._text_parts.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag != "li" or not self._in_li:
            return
        text = re.sub(r"\s+", " ", "".join(self._text_parts)).strip()
        if self._href and "—" in text:
            _, desc = text.split("—", 1)
            self.descriptions[htmllib.unescape(self._href)] = desc.strip()
        self._in_li = False
        self._href = None
        self._text_parts = []


def extract_index_descriptions(index_html: str) -> dict[str, str]:
    parser = IndexDescriptionParser()
    parser.feed(index_html)
    parser.close()
    return parser.descriptions


def escape_script_json(json_text: str) -> str:
    return (
        json_text.replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def collect_page_meta(descriptions: dict[str, str] | None = None) -> list[PageMeta]:
    descriptions = descriptions or {}
    pages: list[PageMeta] = []
    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        for f in sorted(src_dir.glob("*.md")):
            p = load_page(f, cat)
            href = f"{cat}/{f.stem}.html"
            pages.append(
                PageMeta(
                    title=p.title,
                    href=href,
                    category=cat,
                    category_label=CATEGORY_LABELS.get(cat, cat),
                    stem=f.stem,
                    tags=p.fm.tags,
                    date=p.fm.date,
                    description=descriptions.get(href, ""),
                )
            )
    return pages


def collect_index_descriptions(resolver: Resolver) -> tuple[str, dict[str, str]]:
    index_md = (WIKI / "index.md").read_text(encoding="utf-8")
    _fm, body = parse_frontmatter(index_md)
    body_resolved = rewrite_wikilinks(body, resolver, from_cat=None)
    body_with_ids = inject_heading_ids(body_resolved)

    converter = md.Markdown(extensions=["fenced_code", "tables", "attr_list", "sane_lists"], output_format="html5")
    body_html = converter.convert(body_with_ids)
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)
    body_html = re.sub(r"(<table>.*?</table>)", r'<div class="table-wrap">\1</div>', body_html, flags=re.DOTALL)
    return body_html, extract_index_descriptions(body_html)


def collect_graph_data(resolver: Resolver, descriptions: dict[str, str] | None = None) -> dict[str, object]:
    descriptions = descriptions or {}
    nodes: dict[str, GraphNode] = {}
    edges_by_pair: dict[tuple[str, str], str] = {}

    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        for md_path in sorted(src_dir.glob("*.md")):
            page = load_page(md_path, cat)
            node_id = md_path.stem
            href = f"{cat}/{node_id}.html"
            nodes[node_id] = GraphNode(
                id=node_id,
                title=page.title,
                category=cat,
                category_label=CATEGORY_LABELS.get(cat, cat),
                href=href,
                tags=page.fm.tags,
                date=page.fm.date,
                description=descriptions.get(href, ""),
            )

            page_edges: dict[tuple[str, str], str] = {}
            for raw in WIKILINK_RE.findall(page.body_md):
                resolved = resolver.resolve(raw)
                if not resolved:
                    continue
                _target_cat, target_stem = resolved
                if target_stem != node_id:
                    page_edges.setdefault((node_id, target_stem), "wikilink")
            for raw in page.fm.related:
                resolved = resolver.resolve(raw)
                if not resolved:
                    continue
                _target_cat, target_stem = resolved
                if target_stem != node_id:
                    page_edges[(node_id, target_stem)] = "related"
            edges_by_pair.update(page_edges)

    inbound: dict[str, set[str]] = {node_id: set() for node_id in nodes}
    outbound: dict[str, set[str]] = {node_id: set() for node_id in nodes}
    for source, target in edges_by_pair:
        if source not in nodes or target not in nodes:
            continue
        outbound[source].add(target)
        inbound[target].add(source)

    for node_id, node in nodes.items():
        node.inbound = len(inbound[node_id])
        node.outbound = len(outbound[node_id])
        node.degree = len(inbound[node_id] | outbound[node_id])

    edges = [
        GraphEdge(source=source, target=target, kind=kind)
        for (source, target), kind in sorted(edges_by_pair.items())
        if source in nodes and target in nodes
    ]
    return {
        "nodes": [node.__dict__ for node in sorted(nodes.values(), key=lambda n: (n.category, n.title.lower()))],
        "edges": [edge.__dict__ for edge in edges],
        "categories": [
            {
                "id": cat,
                "label": CATEGORY_LABELS.get(cat, cat),
                "count": sum(1 for node in nodes.values() if node.category == cat),
            }
            for cat in CATEGORIES
        ],
    }


def build_topic_groups(pages: list[PageMeta]) -> list[dict[str, object]]:
    by_stem = {p.stem: p for p in pages}
    groups: list[dict[str, object]] = []
    for cfg in TOPIC_GROUPS:
        tagset = cfg["tags"]
        preferred_stems = cfg["preferred"]
        preferred_set = set(preferred_stems)
        matches = [
            p for p in pages
            if tagset.intersection(set(p.tags))
            or any(token in p.title.lower() for token in tagset)
            or p.stem in preferred_set
        ]
        unique: dict[str, PageMeta] = {p.href: p for p in matches}
        ordered = [by_stem[s] for s in preferred_stems if s in by_stem]
        ordered.extend(
            sorted(
                (p for p in unique.values() if p.stem not in preferred_set),
                key=lambda p: (p.category != "analysis", p.title.lower()),
            )
        )
        ordered = list({p.href: p for p in ordered}.values())
        groups.append(
            {
                "slug": cfg["slug"],
                "title": cfg["title"],
                "description": cfg["description"],
                "count": len(ordered),
                "pages": ordered,
                "links": ordered[:4],
            }
        )
    return groups


def find_topic(groups: list[dict[str, object]], slug: str) -> dict[str, object]:
    for group in groups:
        if group.get("slug") == slug:
            return group
    available = ", ".join(str(group.get("slug", "")) for group in groups)
    raise ValueError(f"Unknown topic '{slug}'. Available topics: {available}")


LOG_ENTRY_RE = re.compile(r"^## \[(?P<date>\d{4}-\d{2}-\d{2})\]\s+(?P<kind>[^|]+)\|\s*(?P<title>.+)$")


def sort_log_entries_newest_first(body_md: str) -> str:
    lines = body_md.splitlines(keepends=True)
    prefix: list[str] = []
    entries: list[tuple[str, int, str]] = []
    current_date = ""
    current_index = -1
    current_lines: list[str] = []

    def flush_current() -> None:
        if current_lines:
            entries.append((current_date, current_index, "".join(current_lines)))

    for line_index, line in enumerate(lines):
        m = LOG_ENTRY_RE.match(line.strip())
        if m:
            flush_current()
            current_date = m.group("date")
            current_index = line_index
            current_lines = [line]
            continue
        if current_lines:
            current_lines.append(line)
        else:
            prefix.append(line)
    flush_current()

    entries.sort(key=lambda entry: (entry[0], entry[1]), reverse=True)
    return "".join(prefix) + "".join(entry for _, _, entry in entries)


def parse_recent_updates(limit: int = 8) -> list[dict[str, str]]:
    log_path = WIKI / "log.md"
    if not log_path.exists():
        return []
    indexed_updates: list[tuple[str, int, dict[str, str]]] = []
    for line_index, line in enumerate(log_path.read_text(encoding="utf-8").splitlines()):
        m = LOG_ENTRY_RE.match(line.strip())
        if not m:
            continue
        date = m.group("date")
        indexed_updates.append(
            (
                date,
                line_index,
                {
                    "date": date,
                    "kind": m.group("kind").strip(),
                    "title": m.group("title").strip(),
                    "href": "log.html",
                },
            )
        )
    indexed_updates.sort(key=lambda entry: (entry[0], entry[1]), reverse=True)
    return [update for _, _, update in indexed_updates[:limit]]


def build_site_stats(pages: list[PageMeta]) -> list[tuple[str, int]]:
    return [
        ("全部页面", len(pages)),
        ("实体", sum(1 for p in pages if p.category == "entities")),
        ("概念", sum(1 for p in pages if p.category == "concepts")),
        ("源文件", sum(1 for p in pages if p.category == "sources")),
        ("分析", sum(1 for p in pages if p.category == "analysis")),
    ]


def esc(value: object) -> str:
    return htmllib.escape(str(value), quote=True)


def render_stat_strip(stats: list[tuple[str, int]]) -> str:
    return '<div class="stats-strip">' + "".join(
        f'<div class="stat"><strong>{count}</strong><span>{esc(label)}</span></div>'
        for label, count in stats
    ) + "</div>"


def render_topic_grid(topic_groups: list[dict[str, object]]) -> str:
    cards = []
    for group in topic_groups:
        links = group["links"]
        link_html = "".join(
            f'<a href="{esc(p.href)}">{esc(p.title)}</a>'
            for p in links
        )
        pdf_link = (
            f'<a class="topic-pdf-link" href="pdf/{esc(group["slug"])}.pdf">'
            f'下载 {esc(group["title"])} PDF</a>'
        )
        cards.append(
            '<section class="topic-card">'
            f'<div class="topic-card-head"><h2>{esc(group["title"])}</h2>'
            f'<span>{esc(group["count"])} pages</span></div>'
            f'<p>{esc(group["description"])}</p>'
            f'<div class="topic-links">{link_html}{pdf_link}</div>'
            '</section>'
        )
    return '<div class="topic-grid">' + "".join(cards) + "</div>"


def render_recent_updates(updates: list[dict[str, str]]) -> str:
    if not updates:
        return ""
    items = "".join(
        '<li>'
        f'<time>{esc(item["date"])}</time>'
        f'<a href="{esc(item["href"])}">{esc(item["title"])}</a>'
        f'<span>{esc(item["kind"])}</span>'
        '</li>'
        for item in updates
    )
    return f'<section class="panel recent-updates"><h2>最近更新</h2><ul>{items}</ul></section>'


def render_reading_paths(pages: list[PageMeta]) -> str:
    by_stem = {p.stem: p for p in pages}
    items = []
    for path in READING_PATHS:
        steps = []
        for label, stem in path["steps"]:
            page = by_stem.get(stem)
            if not page:
                continue
            steps.append(
                '<a class="path-step" '
                f'href="{esc(page.href)}">'
                f'<span>{esc(label)}</span>'
                f'<strong>{esc(page.title)}</strong>'
                '</a>'
            )
        if not steps:
            continue
        items.append(
            '<li>'
            f'<div class="path-copy"><strong>{esc(path["title"])}</strong>'
            f'<p>{esc(path["description"])}</p></div>'
            f'<div class="path-steps">{"".join(steps)}</div>'
            '</li>'
        )
    return (
        '<section class="panel reading-paths">'
        '<div class="panel-title-row"><h2>推荐阅读路径</h2><span>按理解路径组织</span></div>'
        '<ol>' + "".join(items) + "</ol></section>"
    )


def html_text(fragment: str) -> str:
    return htmllib.unescape(re.sub(r"<[^>]+>", "", fragment)).strip()


def count_index_items(fragment: str) -> int:
    return len(re.findall(r"<li\b", fragment))


def render_index_subsections(content: str) -> str:
    parts = re.split(r"(<h3[^>]*>.*?</h3>)", content, flags=re.DOTALL)
    if len(parts) == 1:
        return f'<div class="index-list">{content}</div>'

    leading = parts[0].strip()
    sections = []
    if leading:
        sections.append(f'<div class="index-list">{leading}</div>')

    for i in range(1, len(parts), 2):
        heading = parts[i]
        body = parts[i + 1] if i + 1 < len(parts) else ""
        title = html_text(heading)
        count = count_index_items(body)
        count_label = f"{count} 项" if count else ""
        sections.append(
            '<details class="index-sub">'
            f'<summary><span>{esc(title)}</span><small>{esc(count_label)}</small></summary>'
            f'<div class="index-list">{body}</div>'
            '</details>'
        )
    return "".join(sections)


def render_full_index(body_html: str) -> str:
    parts = re.split(r"(<h2[^>]*>.*?</h2>)", body_html, flags=re.DOTALL)
    sections = []
    open_titles = ("实体", "概念", "分析")

    for i in range(1, len(parts), 2):
        heading = parts[i]
        content = parts[i + 1] if i + 1 < len(parts) else ""
        title = html_text(heading)
        count = count_index_items(content)
        open_attr = " open" if any(token in title for token in open_titles) else ""
        sections.append(
            f'<details class="index-major"{open_attr}>'
            f'<summary><span>{esc(title)}</span><small>{count} 项</small></summary>'
            f'<div class="index-major-body">{render_index_subsections(content)}</div>'
            '</details>'
        )

    return (
        '<section class="full-index" id="full-index">'
        '<div class="full-index-head">'
        '<div><h2>完整索引</h2><p>按原始 wiki 索引折叠展示，用于查漏和快速跳转。</p></div>'
        '<div class="full-index-actions">'
        '<button type="button" data-index-expand>全部展开</button>'
        '<button type="button" data-index-collapse>全部收起</button>'
        '</div>'
        '</div>'
        '<div class="index-accordion">'
        + "".join(sections)
        + '</div></section>'
    )


GRAPH_PAGE_SCRIPT = r"""
(() => {
  const data = JSON.parse(document.getElementById("graph-data").textContent);
  const svg = document.getElementById("knowledge-graph");
  const viewport = document.getElementById("graph-viewport");
  const searchInput = document.getElementById("graph-search");
  const resetButton = document.getElementById("graph-reset");
  const detailsButton = document.getElementById("graph-details");
  const zoomInButton = document.getElementById("graph-zoom-in");
  const zoomOutButton = document.getElementById("graph-zoom-out");
  const fitButton = document.getElementById("graph-fit");
  const workbench = document.querySelector(".graph-workbench");
  const inspector = document.getElementById("graph-inspector");
  const totals = document.getElementById("graph-totals");
  const categoryButtons = Array.from(document.querySelectorAll("[data-graph-category]"));
  const nodeById = new Map(data.nodes.map((node) => [node.id, { ...node }]));
  const allEdges = data.edges.filter((edge) => nodeById.has(edge.source) && nodeById.has(edge.target));
  const categories = new Set(data.categories.map((cat) => cat.id));
  const activeCategories = new Set(categories);
  const colorByCategory = {
    entities: "#6ea8fe",
    concepts: "#8ad97a",
    sources: "#f0b75d",
    analysis: "#c99cff",
  };

  let visibleNodes = [];
  let visibleEdges = [];
  let selectedId = null;
  let highlightedId = null;
  let scale = 1;
  let panX = 0;
  let panY = 0;
  let drag = null;
  let panning = null;
  let detailsOpen = false;
  const positionsReady = new Set();
  const initialFocus = new URLSearchParams(window.location.search).get("focus");
  if (initialFocus && nodeById.has(initialFocus)) {
    selectedId = initialFocus;
    searchInput.value = nodeById.get(initialFocus).title;
  }

  const esc = (value) => String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
  const shortLabel = (value) => {
    const text = String(value ?? "");
    return text.length > 26 ? `${text.slice(0, 25)}...` : text;
  };

  function matchesQuery(node, query) {
    if (!query) return true;
    return [node.title, node.id, node.category, node.category_label, node.description, ...(node.tags || [])]
      .join(" ")
      .toLowerCase()
      .includes(query);
  }

  function getVisibleData() {
    const query = searchInput.value.trim().toLowerCase();
    const directMatches = new Set(
      data.nodes
        .filter((node) => activeCategories.has(node.category) && matchesQuery(node, query))
        .map((node) => node.id)
    );
    const visibleIds = new Set(directMatches);

    if (query) {
      for (const edge of allEdges) {
        if (directMatches.has(edge.source) && activeCategories.has(nodeById.get(edge.target).category)) {
          visibleIds.add(edge.target);
        }
        if (directMatches.has(edge.target) && activeCategories.has(nodeById.get(edge.source).category)) {
          visibleIds.add(edge.source);
        }
      }
    }

    const nodes = data.nodes.filter((node) => visibleIds.has(node.id)).map((node) => nodeById.get(node.id));
    const idSet = new Set(nodes.map((node) => node.id));
    const edges = allEdges.filter((edge) => idSet.has(edge.source) && idSet.has(edge.target));
    return { nodes, edges };
  }

  function seedPositions(nodes) {
    const rect = svg.getBoundingClientRect();
    const width = Math.max(rect.width, 720);
    const height = Math.max(rect.height, 620);
    const lanes = Array.from(categories);
    const laneWidth = width / Math.max(lanes.length, 1);
    const ordered = [...nodes].sort((a, b) => (b.degree - a.degree) || a.title.localeCompare(b.title));

    ordered.forEach((node, index) => {
      if (positionsReady.has(node.id)) return;
      const lane = Math.max(0, lanes.indexOf(node.category));
      const row = Math.floor(index / Math.max(lanes.length, 1));
      const jitter = ((index * 37) % 100) / 100;
      node.x = laneWidth * lane + laneWidth * (0.32 + jitter * 0.36);
      node.y = 92 + (row * 92 + jitter * 48) % Math.max(height - 180, 360);
      positionsReady.add(node.id);
    });
  }

  function runLayout(nodes, edges) {
    seedPositions(nodes);
    const rect = svg.getBoundingClientRect();
    const width = Math.max(rect.width, 720);
    const height = Math.max(rect.height, 620);
    const links = edges.map((edge) => [nodeById.get(edge.source), nodeById.get(edge.target)]);

    for (let step = 0; step < 170; step += 1) {
      const alpha = 1 - step / 170;
      for (let i = 0; i < nodes.length; i += 1) {
        const a = nodes[i];
        for (let j = i + 1; j < nodes.length; j += 1) {
          const b = nodes[j];
          let dx = (a.x || 0) - (b.x || 0);
          let dy = (a.y || 0) - (b.y || 0);
          let distance = Math.max(Math.sqrt(dx * dx + dy * dy), 18);
          const force = (1800 / (distance * distance)) * alpha;
          dx /= distance;
          dy /= distance;
          a.x += dx * force;
          a.y += dy * force;
          b.x -= dx * force;
          b.y -= dy * force;
        }
      }

      for (const [source, target] of links) {
        const dx = (target.x || 0) - (source.x || 0);
        const dy = (target.y || 0) - (source.y || 0);
        const distance = Math.max(Math.sqrt(dx * dx + dy * dy), 1);
        const ideal = 122 + Math.min((source.degree + target.degree) * 4, 72);
        const force = (distance - ideal) * 0.014 * alpha;
        const nx = dx / distance;
        const ny = dy / distance;
        source.x += nx * force;
        source.y += ny * force;
        target.x -= nx * force;
        target.y -= ny * force;
      }

      for (const node of nodes) {
        const lane = Array.from(categories).indexOf(node.category);
        const laneX = width * ((lane + 0.5) / Math.max(categories.size, 1));
        node.x += (laneX - node.x) * 0.012 * alpha;
        node.y += (height / 2 - node.y) * 0.006 * alpha;
        node.x = Math.max(42, Math.min(width - 42, node.x));
        node.y = Math.max(42, Math.min(height - 42, node.y));
      }
    }
  }

  function edgeClass(edge) {
    if (!selectedId && !highlightedId) return "";
    const active = selectedId || highlightedId;
    return edge.source === active || edge.target === active ? "is-connected" : "is-dimmed";
  }

  function applyTransform() {
    viewport.setAttribute("transform", `translate(${panX} ${panY}) scale(${scale})`);
  }

  function fitView() {
    if (!visibleNodes.length) {
      scale = 1;
      panX = 0;
      panY = 0;
      applyTransform();
      return;
    }
    const rect = svg.getBoundingClientRect();
    const minX = Math.min(...visibleNodes.map((node) => node.x || 0));
    const maxX = Math.max(...visibleNodes.map((node) => node.x || 0));
    const minY = Math.min(...visibleNodes.map((node) => node.y || 0));
    const maxY = Math.max(...visibleNodes.map((node) => node.y || 0));
    const padding = 30;
    const graphWidth = Math.max(maxX - minX, 1);
    const graphHeight = Math.max(maxY - minY, 1);
    scale = Math.min(
      1.2,
      Math.max(
        0.62,
        Math.min((rect.width - padding * 2) / graphWidth, (rect.height - padding * 2) / graphHeight)
      )
    );
    panX = (rect.width - graphWidth * scale) / 2 - minX * scale;
    panY = (rect.height - graphHeight * scale) / 2 - minY * scale;
    applyTransform();
  }

  function zoomBy(multiplier) {
    const rect = svg.getBoundingClientRect();
    const px = rect.width / 2;
    const py = rect.height / 2;
    const nextScale = Math.min(2.8, Math.max(0.42, scale * multiplier));
    panX = px - (px - panX) * (nextScale / scale);
    panY = py - (py - panY) * (nextScale / scale);
    scale = nextScale;
    applyTransform();
  }

  function nodeRadius(node) {
    return 6 + Math.min(Math.sqrt(Math.max(node.degree, 1)) * 2.6, 13);
  }

  function drawPositions() {
    viewport.querySelectorAll("[data-edge]").forEach((line) => {
      const source = nodeById.get(line.dataset.source);
      const target = nodeById.get(line.dataset.target);
      line.setAttribute("x1", source.x);
      line.setAttribute("y1", source.y);
      line.setAttribute("x2", target.x);
      line.setAttribute("y2", target.y);
    });
    viewport.querySelectorAll("[data-node]").forEach((group) => {
      const node = nodeById.get(group.dataset.node);
      group.setAttribute("transform", `translate(${node.x} ${node.y})`);
    });
  }

  function renderInspector(nodeId) {
    const node = nodeId ? nodeById.get(nodeId) : null;
    if (!node) {
      const top = [...data.nodes].sort((a, b) => b.degree - a.degree).slice(0, 8);
      inspector.innerHTML = `
        <h2>图谱概览</h2>
        <p>${esc(data.nodes.length)} 个页面，${esc(data.edges.length)} 条页面关系。搜索会保留命中页面的一跳邻居，便于理解上下文。</p>
        <h3>高连接页面</h3>
        <div class="graph-link-list">
          ${top.map((item) => `<a href="${esc(item.href)}">${esc(item.title)}<span>${esc(item.category_label)} · ${esc(item.degree)}</span></a>`).join("")}
        </div>
      `;
      return;
    }

    const inbound = visibleEdges.filter((edge) => edge.target === node.id).map((edge) => nodeById.get(edge.source));
    const outbound = visibleEdges.filter((edge) => edge.source === node.id).map((edge) => nodeById.get(edge.target));
    const tags = (node.tags || []).slice(0, 8).map((tag) => `<span class="tag">${esc(tag)}</span>`).join("");
    inspector.innerHTML = `
      <div class="graph-inspector-head">
        <span class="graph-node-kind">${esc(node.category_label)}</span>
        <a href="${esc(node.href)}">打开页面</a>
      </div>
      <h2>${esc(node.title)}</h2>
      ${node.description ? `<p>${esc(node.description)}</p>` : ""}
      <div class="graph-metrics">
        <span><strong>${esc(node.degree)}</strong>连接</span>
        <span><strong>${esc(node.inbound)}</strong>入链</span>
        <span><strong>${esc(node.outbound)}</strong>出链</span>
      </div>
      ${tags ? `<div class="tags">${tags}</div>` : ""}
      <h3>指向它的页面</h3>
      ${renderNodeList(inbound)}
      <h3>它指向的页面</h3>
      ${renderNodeList(outbound)}
    `;
  }

  function renderNodeList(nodes) {
    if (!nodes.length) return '<p class="graph-empty">当前筛选范围内没有关系。</p>';
    return `<div class="graph-link-list">${nodes
      .slice(0, 12)
      .map((item) => `<a href="${esc(item.href)}">${esc(item.title)}<span>${esc(item.category_label)} · ${esc(item.degree)}</span></a>`)
      .join("")}</div>`;
  }

  function render(options = {}) {
    const current = getVisibleData();
    visibleNodes = current.nodes;
    visibleEdges = current.edges;
    if (selectedId && !visibleNodes.some((node) => node.id === selectedId)) selectedId = null;
    runLayout(visibleNodes, visibleEdges);
    viewport.replaceChildren();

    for (const edge of visibleEdges) {
      const source = nodeById.get(edge.source);
      const target = nodeById.get(edge.target);
      const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
      line.dataset.edge = "true";
      line.dataset.source = edge.source;
      line.dataset.target = edge.target;
      line.classList.add("graph-edge");
      if (edge.kind === "related") line.classList.add("is-related");
      const cls = edgeClass(edge);
      if (cls) line.classList.add(cls);
      line.setAttribute("x1", source.x);
      line.setAttribute("y1", source.y);
      line.setAttribute("x2", target.x);
      line.setAttribute("y2", target.y);
      viewport.append(line);
    }

    const connected = new Set();
    if (selectedId || highlightedId) {
      const active = selectedId || highlightedId;
      for (const edge of visibleEdges) {
        if (edge.source === active) connected.add(edge.target);
        if (edge.target === active) connected.add(edge.source);
      }
    }

    for (const node of visibleNodes) {
      const group = document.createElementNS("http://www.w3.org/2000/svg", "g");
      group.classList.add("graph-node");
      if (selectedId === node.id) group.classList.add("is-selected");
      if ((selectedId || highlightedId) && node.id !== (selectedId || highlightedId) && !connected.has(node.id)) {
        group.classList.add("is-dimmed");
      }
      group.dataset.node = node.id;
      group.setAttribute("transform", `translate(${node.x} ${node.y})`);
      group.setAttribute("tabindex", "0");
      group.setAttribute("role", "button");
      group.setAttribute("aria-label", node.title);

      const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
      circle.setAttribute("r", nodeRadius(node));
      circle.setAttribute("fill", colorByCategory[node.category] || "#82b4ff");
      group.append(circle);

      if (node.degree >= 8 || selectedId === node.id || highlightedId === node.id) {
        const label = document.createElementNS("http://www.w3.org/2000/svg", "text");
        label.setAttribute("x", nodeRadius(node) + 7);
        label.setAttribute("y", 4);
        label.textContent = shortLabel(node.title);
        group.append(label);
      }

      group.addEventListener("click", () => {
        selectedId = node.id;
        render();
      });
      group.addEventListener("dblclick", () => {
        window.location.href = node.href;
      });
      group.addEventListener("keydown", (event) => {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          selectedId = node.id;
          render();
        }
      });
      group.addEventListener("pointerdown", (event) => {
        drag = { node, x: event.clientX, y: event.clientY };
        group.setPointerCapture(event.pointerId);
        event.stopPropagation();
      });
      viewport.append(group);
    }

    drawPositions();
    totals.textContent = `${visibleNodes.length} 个页面 · ${visibleEdges.length} 条关系`;
    renderInspector(selectedId);
    if (options.fit) {
      fitView();
    } else {
      applyTransform();
    }
  }

  categoryButtons.forEach((button) => {
    button.addEventListener("click", () => {
      const category = button.dataset.graphCategory;
      if (activeCategories.has(category) && activeCategories.size > 1) {
        activeCategories.delete(category);
      } else {
        activeCategories.add(category);
      }
      button.classList.toggle("is-active", activeCategories.has(category));
      button.setAttribute("aria-pressed", activeCategories.has(category) ? "true" : "false");
      render({ fit: true });
    });
  });

  searchInput.addEventListener("input", () => render({ fit: true }));
  resetButton.addEventListener("click", () => {
    searchInput.value = "";
    selectedId = null;
    highlightedId = null;
    activeCategories.clear();
    categories.forEach((cat) => activeCategories.add(cat));
    categoryButtons.forEach((button) => {
      button.classList.add("is-active");
      button.setAttribute("aria-pressed", "true");
    });
    scale = 1;
    panX = 0;
    panY = 0;
    render({ fit: true });
  });

  detailsButton.addEventListener("click", () => {
    detailsOpen = !detailsOpen;
    workbench.classList.toggle("has-details", detailsOpen);
    detailsButton.textContent = detailsOpen ? "隐藏详情" : "详情";
    detailsButton.setAttribute("aria-pressed", detailsOpen ? "true" : "false");
  });

  zoomInButton.addEventListener("click", () => zoomBy(1.18));
  zoomOutButton.addEventListener("click", () => zoomBy(0.84));
  fitButton.addEventListener("click", fitView);

  svg.addEventListener("pointerdown", (event) => {
    if (event.target !== svg) return;
    panning = { x: event.clientX, y: event.clientY, panX, panY };
    svg.setPointerCapture(event.pointerId);
  });
  svg.addEventListener("pointermove", (event) => {
    if (drag) {
      const dx = (event.clientX - drag.x) / scale;
      const dy = (event.clientY - drag.y) / scale;
      drag.node.x += dx;
      drag.node.y += dy;
      drag.x = event.clientX;
      drag.y = event.clientY;
      drawPositions();
    } else if (panning) {
      panX = panning.panX + event.clientX - panning.x;
      panY = panning.panY + event.clientY - panning.y;
      applyTransform();
    }
  });
  svg.addEventListener("pointerup", () => {
    drag = null;
    panning = null;
  });
  svg.addEventListener("pointercancel", () => {
    drag = null;
    panning = null;
  });
  svg.addEventListener("wheel", (event) => {
    event.preventDefault();
    const rect = svg.getBoundingClientRect();
    const px = event.clientX - rect.left;
    const py = event.clientY - rect.top;
    const nextScale = Math.min(2.8, Math.max(0.42, scale * (event.deltaY > 0 ? 0.92 : 1.08)));
    panX = px - (px - panX) * (nextScale / scale);
    panY = py - (py - panY) * (nextScale / scale);
    scale = nextScale;
    applyTransform();
  }, { passive: false });

  detailsButton.textContent = "详情";
  detailsButton.setAttribute("aria-pressed", "false");
  render({ fit: true });
})();
"""


def build_graph_page(
    graph_data: dict[str, object],
    resolver: Resolver,
    order: list[tuple[str, str]],
) -> str:
    graph_json = escape_script_json(json.dumps(graph_data, ensure_ascii=False, separators=(",", ":")))
    category_buttons = "".join(
        f'<button type="button" class="graph-filter is-active" data-graph-category="{esc(cat["id"])}" aria-pressed="true">'
        f'<span class="graph-filter-dot graph-filter-{esc(cat["id"])}"></span>{esc(cat["label"])}<small>{esc(cat["count"])}</small></button>'
        for cat in graph_data["categories"]
    )
    return f"""<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>知识图谱 · llm-wiki</title>
  <link rel="stylesheet" href="{ASSETS_REL}" />
{AUTO_MARKER}
</head>
<body>

<header class="topbar">
  <a class="brand" href="./index.html"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">知识图谱</span>
  <span class="spacer"></span>
  <span class="meta"><a href="./log.html">操作时间线 →</a></span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<main class="graph-page">
  <section class="graph-workbench">
    <div class="graph-canvas-wrap">
      <div class="graph-canvas-head">
        <div class="graph-tools-primary">
          <strong>知识图谱</strong>
          <span id="graph-totals"></span>
          <label class="sr-only" for="graph-search">搜索页面、标签、分类和描述</label>
          <input id="graph-search" type="search" placeholder="搜索项目、概念、标签" autocomplete="off" />
        </div>
        <div class="graph-filters" aria-label="分类过滤">
          {category_buttons}
        </div>
        <div class="graph-canvas-actions" aria-label="图谱视图控制">
          <button id="graph-details" type="button" aria-pressed="false">详情</button>
          <button id="graph-reset" type="button">重置</button>
          <button id="graph-zoom-out" type="button" aria-label="缩小">−</button>
          <button id="graph-fit" type="button">适配</button>
          <button id="graph-zoom-in" type="button" aria-label="放大">＋</button>
          <a href="./index.html">索引</a>
        </div>
      </div>
      <svg id="knowledge-graph" role="img" aria-label="llm-wiki 页面关系图">
        <g id="graph-viewport"></g>
      </svg>
    </div>
    <aside id="graph-inspector" class="graph-inspector" aria-live="polite"></aside>
  </section>
  {render_root_navigation(resolver, order, include_return=True)}
</main>

<script type="application/json" id="graph-data">{graph_json}</script>
<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});
</script>
<script>{GRAPH_PAGE_SCRIPT}</script>

</body>
</html>
"""


def build_site_index(
    resolver: Resolver,
    body_html: str | None = None,
    descriptions: dict[str, str] | None = None,
    order: list[tuple[str, str]] | None = None,
    pages: list[PageMeta] | None = None,
    topic_groups: list[dict[str, object]] | None = None,
) -> str:
    """Generate wiki/html/index.html — mirrors wiki/index.md structure with search."""
    if body_html is None or descriptions is None:
        body_html, descriptions = collect_index_descriptions(resolver)
    order = order if order is not None else reading_order(resolver)

    # All pages for search index
    pages = pages if pages is not None else collect_page_meta(descriptions)
    topic_groups = topic_groups if topic_groups is not None else build_topic_groups(pages)
    site_stats = build_site_stats(pages)
    recent_updates = parse_recent_updates()
    search_index = [
        {
            "title": p.title,
            "href": p.href,
            "category": p.category,
            "categoryLabel": p.category_label,
            "tags": p.tags,
            "description": p.description,
            "date": p.date,
        }
        for p in pages
    ]
    search_json = escape_script_json(json.dumps(search_index, ensure_ascii=False))

    extra_head = ""

    extra_body = f"""
<section class="home-hero">
  <div>
    <h1>llm-wiki</h1>
    <p class="subtitle">个人 LLM / AI Agent / 云原生 / 推理基础设施知识库。</p>
    <div class="home-actions">
      <a class="button-link" href="./graph.html">打开知识图谱</a>
      <a class="button-link button-link-secondary" href="./log.html">查看操作时间线</a>
    </div>
  </div>
  {render_stat_strip(site_stats)}
</section>

<section class="home-search">
  <label class="sr-only" for="search-input">搜索全站标题、标签、分类和描述</label>
  <input id="search-input" type="search" placeholder="搜索标题、标签、主题、项目" autocomplete="off" />
  <ul id="search-results"></ul>
</section>

<section class="home-section">
  <h2>主题入口</h2>
  {render_topic_grid(topic_groups)}
</section>

<div class="home-panels">
  {render_reading_paths(pages)}
  {render_recent_updates(recent_updates)}
</div>

<script>
  const SEARCH_INDEX = {search_json};
  const input = document.getElementById("search-input");
  const out = document.getElementById("search-results");
  function search(q) {{
    q = q.trim().toLowerCase();
    if (!q) {{ out.replaceChildren(); return; }}
    const hits = SEARCH_INDEX.filter(e => {{
      const tags = (e.tags || []).join(" ");
      return [e.title, e.category, e.categoryLabel, tags, e.description]
        .join(" ")
        .toLowerCase()
        .includes(q);
    }}).slice(0, 30);
    const nodes = [];
    for (const e of hits) {{
      const li = document.createElement("li");
      const link = document.createElement("a");
      link.className = "wikilink";
      link.setAttribute("href", e.href);
      link.textContent = e.title;
      const meta = document.createElement("small");
      const tags = (e.tags || []).slice(0, 4).join(", ");
      meta.textContent = `${{e.categoryLabel}} · ${{tags}}`;
      li.append(link, meta);
      if (e.description) {{
        const description = document.createElement("p");
        description.textContent = e.description;
        li.append(description);
      }}
      nodes.push(li);
    }}
    out.replaceChildren(...nodes);
  }}
  input.addEventListener("input", e => search(e.target.value));
  const fullIndex = document.getElementById("full-index");
  fullIndex?.querySelector("[data-index-expand]")?.addEventListener("click", () => {{
    fullIndex.querySelectorAll("details").forEach(detail => detail.open = true);
  }});
  fullIndex?.querySelector("[data-index-collapse]")?.addEventListener("click", () => {{
    fullIndex.querySelectorAll("details").forEach(detail => detail.open = false);
  }});
</script>

{render_full_index(body_html)}
"""

    page_html = f"""<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>llm-wiki · 知识库索引</title>
  <link rel="stylesheet" href="{ASSETS_REL}" />
{extra_head}
{AUTO_MARKER}
</head>
<body>

<header class="topbar">
  <a class="brand" href="./index.html"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">全站首页</span>
  <span class="spacer"></span>
  <span class="meta"><a href="./graph.html">知识图谱 →</a></span>
  <span class="meta"><a href="./log.html">操作时间线 →</a></span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<div class="layout">
  <main class="content">

  {extra_body}

  {render_root_navigation(resolver, order, include_return=False)}

  <div class="footer">
    🦊 llm-wiki · 由 <code>wiki/html-assets/build.py</code> 自动生成
  </div>
  </main>
</div>

<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});
</script>

</body>
</html>
"""
    return page_html


# ── Driver ───────────────────────────────────────────────────────
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="Overwrite hand-crafted HTML too")
    ap.add_argument("--dry-run", action="store_true")
    pdf_group = ap.add_mutually_exclusive_group()
    pdf_group.add_argument("--pdf-topic", metavar="SLUG", help="Export one topic as PDF")
    pdf_group.add_argument("--pdf-topics", action="store_true", help="Export all topics as PDFs")
    args = ap.parse_args()

    resolver = Resolver()
    order = reading_order(resolver)
    index_body_html, descriptions = collect_index_descriptions(resolver)
    pages = collect_page_meta(descriptions)
    topic_groups = build_topic_groups(pages)
    try:
        selected_topics = (
            [find_topic(topic_groups, args.pdf_topic)]
            if args.pdf_topic
            else topic_groups if args.pdf_topics else []
        )
    except ValueError as exc:
        ap.error(str(exc))

    OUT.mkdir(parents=True, exist_ok=True)
    sync_html_assets(args.dry_run)
    graph_data = collect_graph_data(resolver, descriptions)

    stats = {"written": 0, "skipped": 0, "total": 0}

    # Category pages
    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        dst_dir = OUT / cat
        dst_dir.mkdir(parents=True, exist_ok=True)
        for md_path in sorted(src_dir.glob("*.md")):
            page = load_page(md_path, cat)
            html = build_page(page, resolver, graph_data, order)
            dst = dst_dir / f"{md_path.stem}.html"
            stats["total"] += 1
            if not should_write(dst, args.force):
                normalize_stylesheet_href(dst, args.dry_run)
                navigation_match = re.search(r'<nav class="page-navigation".*?</nav>', html, flags=re.DOTALL)
                inject_navigation_into_handcrafted(
                    dst,
                    navigation_match.group(0) if navigation_match else "",
                    args.dry_run,
                )
                stats["skipped"] += 1
                print(f"  skip (hand-crafted): {dst.relative_to(ROOT)}")
                continue
            if args.dry_run:
                print(f"  would write: {dst.relative_to(ROOT)}")
            else:
                dst.write_text(html, encoding="utf-8")
                stats["written"] += 1
                print(f"  ✓ {dst.relative_to(ROOT)}")

    # log.md → log.html
    log_md = WIKI / "log.md"
    if log_md.exists():
        page = load_page(log_md, "ROOT")
        page.body_md = sort_log_entries_newest_first(page.body_md)
        html = build_page(page, resolver, graph_data, order)
        dst = OUT / "log.html"
        stats["total"] += 1
        if should_write(dst, args.force):
            if not args.dry_run:
                dst.write_text(html, encoding="utf-8")
            stats["written"] += 1
            print(f"  ✓ {dst.relative_to(ROOT)}")
        else:
            stats["skipped"] += 1

    # Site index
    dst = OUT / "index.html"
    stats["total"] += 1
    if should_write(dst, args.force):
        html = build_site_index(
            resolver,
            index_body_html,
            descriptions,
            order,
            pages,
            topic_groups,
        )
        if not args.dry_run:
            dst.write_text(html, encoding="utf-8")
        stats["written"] += 1
        print(f"  ✓ {dst.relative_to(ROOT)}")
    else:
        stats["skipped"] += 1

    # Knowledge graph
    graph_json_dst = OUT / "graph.json"
    if args.dry_run:
        print(f"  would write: {graph_json_dst.relative_to(ROOT)}")
    else:
        graph_json_dst.write_text(json.dumps(graph_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"  ✓ {graph_json_dst.relative_to(ROOT)}")

    dst = OUT / "graph.html"
    stats["total"] += 1
    if should_write(dst, args.force):
        html = build_graph_page(graph_data, resolver, order)
        if args.dry_run:
            print(f"  would write: {dst.relative_to(ROOT)}")
        else:
            dst.write_text(html, encoding="utf-8")
            print(f"  ✓ {dst.relative_to(ROOT)}")
        stats["written"] += 1
    else:
        stats["skipped"] += 1

    try:
        for topic in selected_topics:
            output_path = PDF_OUT / f"{topic['slug']}.pdf"
            if args.dry_run:
                print(f"  would write: {output_path.relative_to(ROOT)}")
            else:
                export_topic_pdf(topic, resolver)
                print(f"  ✓ {output_path.relative_to(ROOT)}")
    except (RuntimeError, OSError, subprocess.CalledProcessError) as exc:
        ap.error(str(exc))

    print(
        f"\nDone. wrote {stats['written']} · skipped {stats['skipped']} (hand-crafted) · total {stats['total']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
