#!/usr/bin/env -S uv run --quiet --with markdown --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["markdown>=3.6"]
# ///
"""
llm-wiki HTML builder.

Walks wiki/{entities,concepts,sources,analysis}/*.md + wiki/{index,log}.md and
generates a mirrored tree under wiki/html/ using the shared style.css.

Hand-crafted HTML pages (e.g. wiki/html/sources/src-nanobot-architecture.html
with Mermaid diagrams) are preserved: build.py only overwrites files that
either don't exist or carry the auto-generated marker.

Run: ./wiki/html-assets/build.py            (idempotent)
     ./wiki/html-assets/build.py --force    (overwrite everything)
"""
from __future__ import annotations

import argparse
import html as htmllib
import json
import re
import sys
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path

import markdown as md

ROOT = Path(__file__).resolve().parent.parent.parent
WIKI = ROOT / "wiki"
OUT = WIKI / "html"
ASSETS_REL = "html-assets/style.css"

AUTO_MARKER = "<!-- generated by wiki/html-assets/build.py -->"

CATEGORIES = ("entities", "concepts", "sources", "analysis")
CATEGORY_LABELS = {
    "entities": "实体",
    "concepts": "概念",
    "sources": "源文件",
    "analysis": "分析",
}

TOPIC_GROUPS = [
    {
        "title": "AI Agent / Memory",
        "description": "长期记忆、MCP、coding agent、Agent framework 与个人 AI 工具链。",
        "tags": {"agent-memory", "ai-agent", "mcp", "claude-code", "agent-framework"},
        "preferred": {
            "agent-memory-project-map",
            "ai-agent-frameworks-map",
            "agent-memory",
            "claude-code",
        },
    },
    {
        "title": "Agent Runtime / Sandbox",
        "description": "Agent 会话编排、沙箱隔离、凭据托管、网关治理和多 Agent 协作。",
        "tags": {"agent-runtime", "agent-sandbox", "sandbox", "multi-agent", "ai-gateway"},
        "preferred": {
            "agent-runtime-sandbox-project-map",
            "agent-sandbox",
            "agentgateway",
            "agent-credential-isolation",
        },
    },
    {
        "title": "LLM Inference / Serving",
        "description": "推理服务、KV cache、PagedAttention、RadixAttention 和多云 GPU 编排。",
        "tags": {"llm-inference", "llm-serving", "kv-cache", "ai-infra", "gpu"},
        "preferred": {
            "llm-inference-serving-project-map",
            "llm-inference",
            "paged-attention",
            "radix-attention",
        },
    },
    {
        "title": "Kubernetes / Cloud Native",
        "description": "Kubernetes、GitOps、controller/operator、GPU 资源栈、安全和可观测。",
        "tags": {"kubernetes", "cloud-native", "gitops", "controller", "operator"},
        "preferred": {
            "kubernetes",
            "gitops",
            "argocd",
            "cloud-native-security",
        },
    },
]


# ── Frontmatter ──────────────────────────────────────────────────
FRONTMATTER_RE = re.compile(r"\A[^\n]*?---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass
class Frontmatter:
    title: str = ""
    tags: list[str] = field(default_factory=list)
    date: str = ""
    sources: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)


def parse_frontmatter(text: str) -> tuple[Frontmatter, str]:
    """Tolerant: accepts garbage chars before the first --- (e.g. kubernetes.md `k2---`)."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return Frontmatter(), text
    raw = m.group(1)
    body = text[m.end():]
    fm = Frontmatter()
    for line in raw.splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k, v = k.strip(), v.strip()
        if not v:
            continue
        if k == "title":
            fm.title = v.strip('"').strip("'")
        elif k == "date":
            fm.date = v.strip('"').strip("'")
        elif k in ("tags", "sources", "related"):
            items = re.findall(r"\[\[([^\]]+)\]\]|\"([^\"]+)\"|'([^']+)'|([^,\[\]\s]+)", v)
            flat = [a or b or c or d for (a, b, c, d) in items]
            flat = [x.strip().strip('"').strip("'").strip("[").strip("]") for x in flat if x]
            flat = [x for x in flat if x]
            setattr(fm, k, flat)
    return fm, body


# ── Wikilink resolution ──────────────────────────────────────────
class Resolver:
    """Index every wiki/*.md by stem → its category (entities/concepts/sources/analysis)."""

    def __init__(self) -> None:
        self.index: dict[str, str] = {}
        for cat in CATEGORIES:
            d = WIKI / cat
            if not d.is_dir():
                continue
            for f in d.glob("*.md"):
                self.index[f.stem] = cat
                self.index[f.stem.lower()] = cat

    def href(self, target: str, *, from_cat: str | None) -> str | None:
        """Return relative href from a page in from_cat to target page; None if not found."""
        stem = target.strip()
        cat = self.index.get(stem) or self.index.get(stem.lower())
        if not cat:
            return None
        # Resolve canonical stem (case-sensitive)
        real_stem = next(
            (f.stem for f in (WIKI / cat).glob("*.md") if f.stem.lower() == stem.lower()),
            stem,
        )
        target_path = f"{cat}/{real_stem}.html"
        if from_cat is None:
            return target_path  # called from wiki/html/index.html
        return f"../{target_path}"


# ── Wikilink preprocessing ───────────────────────────────────────
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


def rewrite_wikilinks(body: str, resolver: Resolver, from_cat: str | None) -> str:
    def repl(m: re.Match) -> str:
        target = m.group(1).strip()
        label = target
        if "|" in target:
            target, label = target.split("|", 1)
            target = target.strip()
            label = label.strip()
        href = resolver.href(target, from_cat=from_cat)
        if href:
            return f'<a class="wikilink" href="{href}">{htmllib.escape(label)}</a>'
        return f'<span class="wikilink wikilink-missing" title="未建页：{htmllib.escape(target)}">{htmllib.escape(label)}</span>'

    return WIKILINK_RE.sub(repl, body)


# ── TOC extraction ───────────────────────────────────────────────
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def slugify(s: str) -> str:
    s = re.sub(r"[<>&\"']+", "", s)
    s = re.sub(r"\s+", "-", s.strip().lower())
    s = re.sub(r"[^a-z0-9\u4e00-\u9fa5\-_]", "", s)
    return s[:80] or "section"


def extract_toc(body: str) -> list[tuple[int, str, str]]:
    """Return [(level, text, slug)] for h2/h3 (skip h1; it's the page title)."""
    toc = []
    seen: dict[str, int] = {}
    for m in HEADING_RE.finditer(body):
        hashes, text = m.group(1), m.group(2)
        level = len(hashes)
        if level < 2 or level > 3:
            continue
        slug = slugify(text)
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 1
        toc.append((level, text, slug))
    return toc


def inject_heading_ids(body: str) -> str:
    """Add {#slug} to h2/h3 so python-markdown's toc extension picks them up."""
    seen: dict[str, int] = {}

    def repl(m: re.Match) -> str:
        hashes, text = m.group(1), m.group(2)
        level = len(hashes)
        if level < 2 or level > 3:
            return m.group(0)
        # Strip wikilink syntax for slugification only
        plain = WIKILINK_RE.sub(r"\1", text)
        slug = slugify(plain)
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 1
        return f"{hashes} {text} {{#{slug}}}"

    return HEADING_RE.sub(repl, body)


# ── HTML shell ───────────────────────────────────────────────────
SHELL = """<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title} · llm-wiki</title>
  <link rel="stylesheet" href="{style_href}" />
  {extra_head}
{auto_marker}
</head>
<body>

<header class="topbar">
  <a class="brand" href="{home_href}"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">{breadcrumb}</span>
  <span class="spacer"></span>
  <span class="meta">{meta_right}</span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<div class="layout">
  <main class="content">

  <h1>{title}</h1>
  {subtitle_html}
  {tags_html}

  {body_html}

  {related_html}

  <div class="footer">
    🦊 llm-wiki · {category_label} · <a href="{md_href}">查看 Markdown 源</a>
  </div>
  </main>

  {toc_html}
</div>

<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});

  const tocLinks = document.querySelectorAll(".toc a");
  const headings = Array.from(document.querySelectorAll("h2[id], h3[id]"));
  function updateActive() {{
    let active = headings[0];
    for (const h of headings) {{
      if (h.getBoundingClientRect().top - 100 <= 0) active = h;
    }}
    if (!active) return;
    tocLinks.forEach((a) =>
      a.classList.toggle("active", a.getAttribute("href") === "#" + active.id)
    );
  }}
  window.addEventListener("scroll", updateActive, {{ passive: true }});
  updateActive();
</script>

</body>
</html>
"""


def render_toc(toc: list[tuple[int, str, str]]) -> str:
    if not toc:
        return ""
    items = []
    for level, text, slug in toc:
        # strip wikilink syntax for TOC label
        label = WIKILINK_RE.sub(r"\1", text)
        cls = "level-3" if level == 3 else ""
        items.append(f'<li class="{cls}"><a href="#{slug}">{htmllib.escape(label)}</a></li>')
    return (
        '<aside class="toc"><h4>本页目录</h4><ul>'
        + "".join(items)
        + "</ul></aside>"
    )


def render_tags(tags: list[str]) -> str:
    if not tags:
        return ""
    chips = "".join(f'<span class="tag">{htmllib.escape(t)}</span>' for t in tags)
    return f'<div class="tags">{chips}</div>'


def render_related(items: list[str], resolver: Resolver, from_cat: str | None) -> str:
    if not items:
        return ""
    lis = []
    for raw in items:
        target = raw.strip().strip("[").strip("]").strip()
        if not target:
            continue
        href = resolver.href(target, from_cat=from_cat)
        if href:
            lis.append(f'<li><a class="wikilink" href="{href}">{htmllib.escape(target)}</a></li>')
        else:
            lis.append(
                f'<li><span class="wikilink wikilink-missing" title="未建页：{htmllib.escape(target)}">'
                f'{htmllib.escape(target)}</span></li>'
            )
    return f'<h2 id="related-frontmatter">相关页面（来自 frontmatter）</h2><ul>{"".join(lis)}</ul>'


def render_subtitle(fm: Frontmatter) -> str:
    parts = []
    if fm.date:
        parts.append(htmllib.escape(fm.date))
    if fm.sources:
        srcs = "、".join(htmllib.escape(s) for s in fm.sources)
        parts.append(f"来源：{srcs}")
    if not parts:
        return ""
    return f'<p class="subtitle">{" · ".join(parts)}</p>'


# ── Page builder ─────────────────────────────────────────────────
@dataclass
class Page:
    md_path: Path
    category: str  # entities / concepts / sources / analysis / ROOT (for index/log)
    fm: Frontmatter
    body_md: str
    title: str


@dataclass
class PageMeta:
    title: str
    href: str
    category: str
    category_label: str
    stem: str
    tags: list[str]
    date: str
    description: str = ""


def build_page(page: Page, resolver: Resolver) -> str:
    body_with_ids = inject_heading_ids(page.body_md)
    body_with_links = rewrite_wikilinks(body_with_ids, resolver, from_cat=page.category if page.category != "ROOT" else None)

    # Markdown → HTML
    converter = md.Markdown(
        extensions=["fenced_code", "tables", "attr_list", "admonition", "sane_lists", "nl2br"],
        output_format="html5",
    )
    body_html = converter.convert(body_with_links)

    # Drop the first <h1> if present; we render our own
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)

    toc = extract_toc(page.body_md)
    toc_html = render_toc(toc)

    is_root = page.category == "ROOT"
    style_href = f"../{ASSETS_REL}" if is_root else f"../../{ASSETS_REL}"
    home_href = "./index.html" if is_root else "../index.html"
    md_href = f"../{page.md_path.name}" if is_root else f"../../{page.category}/{page.md_path.name}"
    breadcrumb = "wiki" if is_root else f"wiki · {page.category}"
    meta_right = page.fm.date or ""
    category_label = "ROOT" if is_root else page.category

    return SHELL.format(
        title=htmllib.escape(page.title),
        style_href=style_href,
        extra_head="",
        auto_marker=AUTO_MARKER,
        home_href=home_href,
        breadcrumb=htmllib.escape(breadcrumb),
        meta_right=htmllib.escape(meta_right),
        subtitle_html=render_subtitle(page.fm),
        tags_html=render_tags(page.fm.tags),
        body_html=body_html,
        related_html=render_related(page.fm.related, resolver, from_cat=page.category if not is_root else None),
        category_label=category_label,
        md_href=md_href,
        toc_html=toc_html,
    )


def load_page(md_path: Path, category: str) -> Page:
    text = md_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    # Title: frontmatter title > first h1 > filename
    title = fm.title
    if not title:
        h1 = re.search(r"^#\s+(.+?)\s*$", body, re.MULTILINE)
        title = h1.group(1).strip() if h1 else md_path.stem
    return Page(md_path=md_path, category=category, fm=fm, body_md=body, title=title)


def should_write(dst: Path, force: bool) -> bool:
    if force or not dst.exists():
        return True
    head = dst.read_text(encoding="utf-8", errors="replace")[:2000]
    return AUTO_MARKER in head


# ── Site index page ──────────────────────────────────────────────
class IndexDescriptionParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.descriptions: dict[str, str] = {}
        self._in_li = False
        self._href: str | None = None
        self._text_parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attrs_dict = dict(attrs)
        if tag == "li":
            self._in_li = True
            self._href = None
            self._text_parts = []
            return
        if tag == "a" and self._in_li and self._href is None:
            classes = (attrs_dict.get("class") or "").split()
            href = attrs_dict.get("href")
            if "wikilink" in classes and href:
                self._href = href

    def handle_data(self, data: str) -> None:
        if self._in_li:
            self._text_parts.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag != "li" or not self._in_li:
            return
        text = re.sub(r"\s+", " ", "".join(self._text_parts)).strip()
        if self._href and "—" in text:
            _, desc = text.split("—", 1)
            self.descriptions[htmllib.unescape(self._href)] = desc.strip()
        self._in_li = False
        self._href = None
        self._text_parts = []


def extract_index_descriptions(index_html: str) -> dict[str, str]:
    parser = IndexDescriptionParser()
    parser.feed(index_html)
    parser.close()
    return parser.descriptions


def escape_script_json(json_text: str) -> str:
    return (
        json_text.replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def collect_page_meta(descriptions: dict[str, str] | None = None) -> list[PageMeta]:
    descriptions = descriptions or {}
    pages: list[PageMeta] = []
    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        for f in sorted(src_dir.glob("*.md")):
            p = load_page(f, cat)
            href = f"{cat}/{f.stem}.html"
            pages.append(
                PageMeta(
                    title=p.title,
                    href=href,
                    category=cat,
                    category_label=CATEGORY_LABELS.get(cat, cat),
                    stem=f.stem,
                    tags=p.fm.tags,
                    date=p.fm.date,
                    description=descriptions.get(href, ""),
                )
            )
    return pages


def build_topic_groups(pages: list[PageMeta]) -> list[dict[str, object]]:
    by_stem = {p.stem: p for p in pages}
    groups: list[dict[str, object]] = []
    for cfg in TOPIC_GROUPS:
        tagset = cfg["tags"]
        preferred_stems = cfg["preferred"]
        matches = [
            p for p in pages
            if tagset.intersection(set(p.tags))
            or any(token in p.title.lower() for token in tagset)
            or p.stem in preferred_stems
        ]
        unique: dict[str, PageMeta] = {p.href: p for p in matches}
        ordered = [by_stem[s] for s in preferred_stems if s in by_stem]
        ordered.extend(
            sorted(
                (p for p in unique.values() if p.stem not in preferred_stems),
                key=lambda p: (p.category != "analysis", p.title.lower()),
            )
        )
        groups.append(
            {
                "title": cfg["title"],
                "description": cfg["description"],
                "count": len(unique),
                "links": ordered[:4],
            }
        )
    return groups


LOG_ENTRY_RE = re.compile(r"^## \[(?P<date>\d{4}-\d{2}-\d{2})\]\s+(?P<kind>[^|]+)\|\s*(?P<title>.+)$")


def parse_recent_updates(limit: int = 8) -> list[dict[str, str]]:
    log_path = WIKI / "log.md"
    if not log_path.exists():
        return []
    updates: list[dict[str, str]] = []
    for line in log_path.read_text(encoding="utf-8").splitlines():
        m = LOG_ENTRY_RE.match(line.strip())
        if not m:
            continue
        updates.append(
            {
                "date": m.group("date"),
                "kind": m.group("kind").strip(),
                "title": m.group("title").strip(),
                "href": "log.html",
            }
        )
    return updates[:limit]


def build_site_stats(pages: list[PageMeta]) -> list[tuple[str, int]]:
    return [
        ("全部页面", len(pages)),
        ("实体", sum(1 for p in pages if p.category == "entities")),
        ("概念", sum(1 for p in pages if p.category == "concepts")),
        ("源文件", sum(1 for p in pages if p.category == "sources")),
        ("分析", sum(1 for p in pages if p.category == "analysis")),
    ]


def build_site_index(resolver: Resolver) -> str:
    """Generate wiki/html/index.html — mirrors wiki/index.md structure with search."""
    index_md = (WIKI / "index.md").read_text(encoding="utf-8")
    fm, body = parse_frontmatter(index_md)

    # Replace [[X]] with anchors to the resolved page (from_cat=None → top-level path)
    body_resolved = rewrite_wikilinks(body, resolver, from_cat=None)
    body_with_ids = inject_heading_ids(body_resolved)

    converter = md.Markdown(extensions=["fenced_code", "tables", "attr_list", "sane_lists"], output_format="html5")
    body_html = converter.convert(body_with_ids)
    body_html = re.sub(r"<h1[^>]*>.*?</h1>\s*", "", body_html, count=1, flags=re.DOTALL)
    descriptions = extract_index_descriptions(body_html)

    # All pages for search index
    pages = collect_page_meta(descriptions)
    topic_groups = build_topic_groups(pages)
    site_stats = build_site_stats(pages)
    recent_updates = parse_recent_updates()
    search_index = [
        {
            "title": p.title,
            "href": p.href,
            "category": p.category,
            "categoryLabel": p.category_label,
            "tags": p.tags,
            "description": p.description,
            "date": p.date,
        }
        for p in pages
    ]
    search_json = escape_script_json(json.dumps(search_index, ensure_ascii=False))

    extra_head = f"""<style>
  .search-box {{
    margin: 16px 0 24px;
    display: flex;
    gap: 8px;
  }}
  .search-box input {{
    flex: 1;
    padding: 10px 14px;
    font-family: var(--font-sans);
    font-size: 14px;
    background: var(--bg-elev);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    color: var(--fg);
    outline: none;
  }}
  .search-box input:focus {{ border-color: var(--accent); }}
  #search-results {{
    margin: 16px 0 0;
    padding: 0;
    list-style: none;
  }}
  #search-results li {{
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
  }}
  #search-results li small {{ color: var(--fg-dim); margin-left: 8px; }}
  #search-results:empty {{ display: none; }}
</style>"""

    extra_body = f"""
<div class="search-box">
  <input id="search-input" type="search" placeholder="搜索全站标题 / 标签 …" autocomplete="off" />
</div>
<ul id="search-results"></ul>

<script>
  const SEARCH_INDEX = {search_json};
  const input = document.getElementById("search-input");
  const out = document.getElementById("search-results");
  function search(q) {{
    q = q.trim().toLowerCase();
    if (!q) {{ out.replaceChildren(); return; }}
    const hits = SEARCH_INDEX.filter(e =>
      e.title.toLowerCase().includes(q) || e.tags.join(",").toLowerCase().includes(q)
    ).slice(0, 30);
    out.replaceChildren(...hits.map(e => {{
      const li = document.createElement("li");
      const link = document.createElement("a");
      link.className = "wikilink";
      link.setAttribute("href", e.href);
      link.textContent = e.title;
      const meta = document.createElement("small");
      meta.textContent = `${{e.category}} · ${{e.tags.join(",")}}`;
      li.append(link, meta);
      return li;
    }}));
  }}
  input.addEventListener("input", e => search(e.target.value));
</script>
"""

    page_html = f"""<!doctype html>
<html lang="zh-CN" data-theme="dark">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>llm-wiki · 知识库索引</title>
  <link rel="stylesheet" href="../{ASSETS_REL}" />
  {extra_head}
{AUTO_MARKER}
</head>
<body>

<header class="topbar">
  <a class="brand" href="./index.html"><span class="brand-dot"></span>llm-wiki</a>
  <span class="meta">全站首页</span>
  <span class="spacer"></span>
  <span class="meta"><a href="./log.html">操作时间线 →</a></span>
  <button id="theme-toggle" aria-label="切换主题">🌓 主题</button>
</header>

<div class="layout">
  <main class="content">

  <h1>🦊 llm-wiki</h1>
  <p class="subtitle">个人 LLM / 云原生 / Agent 知识库 · 全站静态渲染 · 暗 / 亮主题切换</p>

  {extra_body}

  {body_html}

  <div class="footer">
    🦊 llm-wiki · 由 <code>wiki/html-assets/build.py</code> 自动生成
  </div>
  </main>
</div>

<script>
  const root = document.documentElement;
  const saved = localStorage.getItem("wiki-theme");
  if (saved) root.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").addEventListener("click", () => {{
    const cur = root.getAttribute("data-theme") || "dark";
    root.setAttribute("data-theme", cur === "dark" ? "light" : "dark");
    localStorage.setItem("wiki-theme", root.getAttribute("data-theme"));
  }});
</script>

</body>
</html>
"""
    return page_html


# ── Driver ───────────────────────────────────────────────────────
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="Overwrite hand-crafted HTML too")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    resolver = Resolver()
    OUT.mkdir(parents=True, exist_ok=True)

    stats = {"written": 0, "skipped": 0, "total": 0}

    # Category pages
    for cat in CATEGORIES:
        src_dir = WIKI / cat
        if not src_dir.is_dir():
            continue
        dst_dir = OUT / cat
        dst_dir.mkdir(parents=True, exist_ok=True)
        for md_path in sorted(src_dir.glob("*.md")):
            page = load_page(md_path, cat)
            html = build_page(page, resolver)
            dst = dst_dir / f"{md_path.stem}.html"
            stats["total"] += 1
            if not should_write(dst, args.force):
                stats["skipped"] += 1
                print(f"  skip (hand-crafted): {dst.relative_to(ROOT)}")
                continue
            if args.dry_run:
                print(f"  would write: {dst.relative_to(ROOT)}")
            else:
                dst.write_text(html, encoding="utf-8")
                stats["written"] += 1
                print(f"  ✓ {dst.relative_to(ROOT)}")

    # log.md → log.html
    log_md = WIKI / "log.md"
    if log_md.exists():
        page = load_page(log_md, "ROOT")
        html = build_page(page, resolver)
        dst = OUT / "log.html"
        stats["total"] += 1
        if should_write(dst, args.force):
            if not args.dry_run:
                dst.write_text(html, encoding="utf-8")
            stats["written"] += 1
            print(f"  ✓ {dst.relative_to(ROOT)}")
        else:
            stats["skipped"] += 1

    # Site index
    dst = OUT / "index.html"
    stats["total"] += 1
    if should_write(dst, args.force):
        html = build_site_index(resolver)
        if not args.dry_run:
            dst.write_text(html, encoding="utf-8")
        stats["written"] += 1
        print(f"  ✓ {dst.relative_to(ROOT)}")
    else:
        stats["skipped"] += 1

    print(
        f"\nDone. wrote {stats['written']} · skipped {stats['skipped']} (hand-crafted) · total {stats['total']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
